OY2-13439  Dynamically calculate % change for S2P1 in Carts
CMSgov/cms-carts-seds pull request #1196
Opened 2021-11-07 19:10 UTC by abelzer212

This code should be temporary, and is absolutely the worst way to do this kind of change, but it's a one off, and my intention is to change it as soon as we do the CARTS rewrite

2021-11-07 20:18 UTC, benjaminpaige approved these changes
No worries. We've all done something similar in this project. If it works, im 👍

2021-11-08 15:24 UTC, gitsierra approved these changes
👍

2021-11-08 15:37 UTC, 13bfrancis requested changes

2021-11-08 15:45 UTC, 13bfrancis approved these changes

2021-12-17 16:31 UTC, closed without merging