Enable field 2 in Basic State Information
CMSgov/cms-carts-seds pull request #139460
Opened 2023-09-19 14:19 UTC by gmrabian

### Description

### Related ticket(s)

MDCT-

---
### How to test

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2023-09-19 15:47 UTC, gmrabian commented on services/app-api/handlers/formTemplates/post.ts
> -      programType: state.programType,
more investigation needed on this needed but for now I don't see a strong case for programType being in state statuses. If we want to keep it we will have to include programType that in the update call.

2023-09-19 15:53 UTC, gmrabian reviewed
Initial refactor. There are other places that use programType differently and will need to be remedied. This is just a start.

2023-09-19 16:28 UTC, BearHanded commented on services/app-api/handlers/formTemplates/post.ts
> -      programType: state.programType,
I am leaning towards keeping it and updating it, mostly because it is something that is currently being fed to kafka and it keeps any downstream consumption the same.

2023-09-19 16:29 UTC, BearHanded commented on services/ui-src/src/store/formData.js
> -        }
If it is already pre-set, this is fine, as long as we show it works.

2023-09-19 16:31 UTC, BearHanded commented on services/ui-src/src/util/shouldDisplay.js
> +    programType ?? selectFragmentById(state, "2023-00-a-01-02").answer.entry;
this works across sections right? Haven't pulled it down to test.

This is also explicitly calling out the year hear which won't work on older forms

2023-09-19 16:47 UTC, BearHanded commented on services/ui-src/src/store/formData.js
> -        }
Does this also mean things get weird if we make this change and items have been previously mis-aligned?

2023-09-19 17:38 UTC, gmrabian commented on services/ui-src/src/util/shouldDisplay.js
> +    programType ?? selectFragmentById(state, "2023-00-a-01-02").answer.entry;
I fixed this to read year from the formYear and verified it reads correctly across previous years. Also ran through all sections in 2023 and they rendered with the conditionals as expected (did not check previous years yet)

2023-09-21 16:38 UTC, gmrabian reviewed
Check it out!

2023-09-21 16:38 UTC, gmrabian commented on services/app-api/handlers/section/update.ts
> +const PROGRAM_TYPE_QUESTION_ID = "-00-a-01-02";
this is the only place this is used so I left it here rather than in a constants file

2023-09-21 16:38 UTC, gmrabian commented on services/app-api/handlers/section/update.ts
> +};
checks current and previous year for updated programType from form, otherwise uses existing programType from status. I simplified the frontend to only read programType from status so this keeps everything in sync behind the scenes

2023-09-21 16:38 UTC, gmrabian commented on services/ui-src/src/components/layout/Part.js
> +    show: shouldDisplay(state, contextData),
programType is no longer needed as an argument for shouldDisplay so we can eliminate two functions from this file and really simplify things

2023-09-21 16:38 UTC, gmrabian commented on services/ui-src/src/store/stateUser.js
> -  programType: programObject.programType,
we don't want programType available in state information because that table has static values for programType

2023-09-21 16:38 UTC, gmrabian commented on services/ui-src/src/util/shouldDisplay.js
> +    const program = state.reportStatus[reportStatusCode].programType;
greatly simplifies logic in this function. all users can access programType from report status now so that is the only place we need look for it

2023-09-21 17:43 UTC, BearHanded approved these changes, later dismissed
Looked at this pretty thoroughly, and this looks solid, but I haven't had a chance to run it locally. Will update if I do.

2023-09-21 20:32 UTC, benmartin-coforma submitted a review, later dismissed
Very nice. Especially like that you updated the shouldDisplay tests for clarity 👍

2023-09-25 13:51 UTC, BearHanded requested changes
Ran this locally and tested it against rendering sections. I am seeing that the browser needs to refresh before rendering the new state for a section.

Replication steps:
- Start with the report as a "combo"
- Switch to Medicaid Expansion CHIP Only
- Navigate to 3F - The form appears when it shouldn't
- Refresh, you should now see the correct state

2023-09-25 17:48 UTC, BearHanded approved these changes

2023-09-25 17:56 UTC, benmartin-coforma approved these changes

2023-09-25 19:26 UTC, merged