[MDCT-2920] [MDCT-2922] Section F & G
CMSgov/cms-carts-seds pull request #139454
Opened 2023-09-15 18:39 UTC by BearHanded

### Description

Section 3 - F & G

### Related ticket(s)

MDCT-2920
MDCT-2922

---
### How to test

Compare the diff to the changes requested in the ticket, proofread, then spin it up.

### Important updates

---
### Author checklist

- [x] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2023-09-15 22:03 UTC, britt-mo commented on services/database/data/seed/seed-section-base-2023.json
>                              "answer": {
lowercase `s` here

2023-09-15 22:04 UTC, britt-mo commented on services/database/data/seed/seed-section-base-2023.json
> +                            "label": "How many children were enrolled in Separate CHIP for at least 90 continuous days during FFY 2023?",
I think this is a lowercase `s`?

2023-09-18 15:11 UTC, BearHanded commented on services/database/data/seed/seed-section-base-2023.json
> +                            "label": "How many children were enrolled in Separate CHIP for at least 90 continuous days during FFY 2023?",
good catch, thank you

2023-09-18 16:05 UTC, gmrabian requested changes
some notes to find out from product

2023-09-18 16:05 UTC, gmrabian commented on services/database/data/seed/seed-section-base-2023.json
> +                "text": "Tell us about the children receiving dental benefits in your Separate CHIP program. Include children who are receiving full benefits and those who are only receiving suppleme
lowercase "separate"

2023-09-19 13:31 UTC, BearHanded commented on services/database/data/seed/seed-section-base-2023.json
> +                        "label": "How many cases were referred to appropriate law enforcement officials in FFY 2023?",
Clarified, this needs to be as shown in the ticket text.

2023-09-19 16:52 UTC, BearHanded commented on services/database/data/seed/seed-section-base-2023.json
> +                        "label": "What safeguards and procedures do the managed care plans have in place?",
Text removed in ticket. Field should remain a text field

2023-09-20 13:29 UTC, benmartin-coforma approved these changes
I haven't spun this up, but the code seems to cover all of the requested changes.

2023-09-20 14:02 UTC, gmrabian approved these changes

2023-09-20 14:03 UTC, merged