MDCT-2914: FFY 2023 Content Changes (Section 3C)
CMSgov/cms-carts-seds pull request #139451
Opened 2023-09-15 15:14 UTC by karla-vm

### Description

Content updates to reflect copy for FFY 2023 in Section 3C of CARTS.

### Related ticket(s)

MDCT-2914

---
### How to test

- Log in as `cms.admin@test.com`
- Generate form base templates for both 2022 and 2023
- Log in as `stateuser2@test.com`
- Navigate to the 2023 form, Section 3C

Verify that the content in red (on the ticket) matches the content in the form

### Important updates

N/A

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2023-09-15 17:23 UTC, BearHanded submitted a review, later dismissed

2023-09-18 14:29 UTC, gmrabian requested changes
Also want to call out the first paragraph of text in "Helpful hints on age groups" differs between the ticket and what's currently in CARTS (even though the ticket indicates no change)

2023-09-18 14:29 UTC, gmrabian commented on services/database/data/seed/seed-section-base-2023.json
> +                    "hint": "Don’t include applicants being considered for redetermination — these data will be collected in Part 3. \n\nPlease note: numbers reported in questions 2-4 of this part ar
First sentence here differs:
ticket – Don’t include applicants who are being considered for redetermination — these data will be collected in Part 3.
text – Don’t include applicants being considered for redetermination — these data will be collected in Part 3. 

diff: "who are"

2023-09-18 14:29 UTC, gmrabian commented on services/database/data/seed/seed-section-base-2023.json
> +                "text": "Tracking a cohort of children enrolled in CHIP (Title XXI) will indicate how long a specific group of children stays enrolled over an 18-month period. This information is req
"you'll report on the same cohort for their enrollment status 12 months later"

In the ticket "same cohort" here is italicized

2023-09-18 14:29 UTC, gmrabian commented on services/database/data/seed/seed-section-base-2023.json
> +                "text": "Tracking a cohort of children enrolled in Medicaid (Title XIX) will indicate how long a specific group of children stays enrolled over an 18-month period. This information is
same note about italicizing "same cohort"

2023-09-18 14:47 UTC, karla-vm commented
> Also want to call out the first paragraph of text in "Helpful hints on age groups" differs between the ticket and what's currently in CARTS (even though the ticket indicates no change)

Great catch, I've updated this to match the ticket 🙏🏽

2023-09-18 14:48 UTC, karla-vm commented on services/database/data/seed/seed-section-base-2023.json
> +                "text": "Tracking a cohort of children enrolled in Medicaid (Title XIX) will indicate how long a specific group of children stays enrolled over an 18-month period. This information is
DK mentioned we won't need the italics in these hints, apologies for not calling that out before!

2023-09-18 14:48 UTC, karla-vm commented on services/database/data/seed/seed-section-base-2023.json
> +                "text": "Tracking a cohort of children enrolled in CHIP (Title XXI) will indicate how long a specific group of children stays enrolled over an 18-month period. This information is req
Same here.

2023-09-18 17:27 UTC, gmrabian submitted a review, later dismissed

2023-09-18 17:50 UTC, BearHanded approved these changes, later dismissed

2023-09-18 21:03 UTC, BearHanded approved these changes

2023-09-19 13:15 UTC, merged