MDCT-2925: FFY 2023 Content Changes (Section 4)
CMSgov/cms-carts-seds pull request #139459
Opened 2023-09-18 20:52 UTC by karla-vm

### Description

Content updates to reflect copy for FFY 2023 in Section 4 of CARTS.

### Related ticket(s)

MDCT-2925

---
### How to test

- Log in as `cms.admin@test.com`
- Generate form base templates for both 2022 and 2023
- Log in as `stateuser2@test.com`
- Navigate to the 2023 form, Section 4

Verify that the content in red (on the ticket) matches the content in the form

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2023-09-18 21:15 UTC, BearHanded submitted a review, later dismissed

2023-09-19 18:41 UTC, gmrabian requested changes
just one typo

2023-09-19 18:41 UTC, gmrabian commented on services/database/data/seed/seed-section-base-2023.json
> +                "text": "Please tell us about the progress you’ve made on your performance goals in the past year. The objectives and goals you add to this section should match those reflected in you
fourth word from the end: "yout" should be "your"

2023-09-19 20:16 UTC, karla-vm commented on services/database/data/seed/seed-section-base-2023.json
> +                "text": "Please tell us about the progress you’ve made on your performance goals in the past year. The objectives and goals you add to this section should match those reflected in you
👑 you dropped this.

2023-09-19 20:28 UTC, BearHanded approved these changes

2023-09-20 15:20 UTC, gmrabian approved these changes

2023-09-20 15:22 UTC, merged