[DO NOT MERGE] - [WIP] - Upgrade carts-bigmac-streams to AWS SDK v3
CMSgov/cms-carts-seds pull request #139520
Opened 2023-11-21 16:18 UTC by benmartin-coforma

### Description
This PR replaces all code specific to AWS SDK v2 within services/carts-bigmac-streams with code that consumes AWS SDK v3 instead.

WORK IN PROGRESS - this code has not been tested.

### Related ticket(s)
CMDCT-2689

---
### How to test
TODO

### Important updates
n/a

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary

2024-04-16 21:08 UTC, benmartin-coforma commented
As author I can't officially approve, but this looks good 👍

2024-04-18 14:54 UTC, BearHanded requested changes, later dismissed
Tested this yesterday, and saw the antivirus scan was erroring. Sent the logs along. Really not sure what is falling apart but it fails to get the file from the s3 bucket.

2024-04-19 15:14 UTC, gmrabian commented
Fixed the scanner. We weren't returning the temporary path for clamav to consume

![Screenshot 2024-04-19 at 11 13 23 AM](https://github.com/Enterprise-CMCS/macpro-mdct-carts/assets/57802560/7513d7b1-7f69-4c30-8855-654df00538f9)

2024-04-22 14:57 UTC, BearHanded approved these changes

2024-04-22 19:52 UTC, dwhitestratiform approved these changes

2024-04-22 19:53 UTC, berryd approved these changes

2024-04-22 19:55 UTC, merged