[CMDCT-3817] Upgrade React-Router-Dom
CMSgov/cms-carts-seds pull request #139753
Opened 2024-08-22 16:55 UTC by ntsummers1

### Description

The long await react-router upgrade is here, and the fruits of our labor can finally be fully observed. Bask in the hooks that make this a lot easier to use router!

### Related ticket(s)

CMDCT-3817

---
### How to test

Log in as a stateuser
Enter a report
Navigate through the sections, clicking any buttons you see to go to different pages. I.E., check the Sidebar, the print actions button on the bottom, the navigation buttons on the bottom, etc.
If everything loads, fill in some data and make sure it saves
Use the top right menu to check that your state user info shows up in the account page
Click the banner image to see you navigate to the root page
Sign out
Sign in as an admin
Repeat the same steps as above and it should all work

### Notes

React-Router is removed
React-Router-Dom 5 -> 6.21

---
### Pre-review checklist

- [x] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [x] I have updated relevant documentation, if necessary
- [x] I have performed a self-review of my code
- [x] I have manually tested this PR in the deployed cloud environment

---
### Pre-merge checklist

#### Review
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

2024-08-28 16:57 UTC, gmrabian requested changes
Blocking due to issue with user timeout

2024-08-28 16:57 UTC, gmrabian commented on services/ui-src/src/components/layout/FormNavigation.test.jsx
> +  useNavigate: () => ({
nit: since `useHistoryPush` is defined but never referenced elsewhere, and since we aren't using "history" anymore per say, could we switch this to jest.fn() and remove that variable?

2024-08-28 16:57 UTC, gmrabian commented on services/ui-src/src/components/layout/TableOfContents.test.jsx
> +  it.only("should navigate on click", async () => {
did you mean to leave the .only?

2024-08-28 16:57 UTC, gmrabian commented on services/ui-src/src/components/layout/Timeout.test.jsx
> -  });
why are we no longer testing for these?

2024-08-28 16:57 UTC, gmrabian commented on services/ui-src/src/components/layout/Timeout.jsx
> +  }, [location]);
the timeout isn't working as expected and I'm wondering if this might be why? it's listening on location and location won't change if you are not using the page

steps to reproduce:
1. in `authLifecycle` change IDLE_WINDOW from 30 to 1 and PROMPT_AT from 29 to 0.5
2. Log in and let sit until the modal pops up
3. The modal displays and says you will be logged out in 59 seconds. The time never changes and it does not change the view after that time

2024-08-28 16:57 UTC, gmrabian commented on services/ui-src/src/components/layout/HomeCMS.jsx
> +    </Routes>
Just a thought in reviewing these: is it normal to control routes by user type? or to have all routes and restrict them on a component level by type? just curious

2024-08-28 16:57 UTC, gmrabian commented on services/ui-src/src/components/layout/Header.jsx
> +                          href="javascript:void(0);"
🤷

2024-09-12 13:23 UTC, ntsummers1 commented on services/ui-src/src/components/layout/FormNavigation.test.jsx
> +  useNavigate: () => ({
Good Call!

2024-09-12 13:23 UTC, ntsummers1 commented on services/ui-src/src/components/layout/TableOfContents.test.jsx
> +  it.only("should navigate on click", async () => {
🌮

2025-03-05 22:30 UTC, ntsummers1 commented on services/ui-src/src/components/layout/Header.jsx
> +                          href="javascript:void(0);"
Fixed :D. Got it working properly with refs, and cleared the old console errors!

2025-03-12 18:04 UTC, gmrabian submitted a review, later dismissed
Didn't see any issues! 👏

2025-03-12 18:04 UTC, gmrabian commented on services/ui-src/src/App.jsx
> +    window.location.pathname.split("/")[1] === "coming-soon" ? (
do these need to be at that location in the path, or could we just do
`window.location.pathname.includes("reports")` or similar?

I do see AppRoutes has a `/state-reports` path so maybe that won't work

also when would we see the `/reports` or `/coming-soon` pages? I am not familiar with those

2025-03-12 20:44 UTC, ntsummers1 commented on services/ui-src/src/App.jsx
> +    window.location.pathname.split("/")[1] === "coming-soon" ? (
Removed it. Forgot to get rid of this unneccessary code. Theres no assocaited links to them!

2025-03-12 20:48 UTC, ntsummers1 commented on services/ui-src/src/components/layout/Timeout.jsx
> +  }, [location]);
Timeout should be working now! And it counts down and navigates correctly too 👀.

2025-03-12 20:50 UTC, ntsummers1 commented on services/ui-src/src/components/sections/homepage/Homepage.jsx
> +              {Object.values(reportStatus).map(formatStateStatus)}
This is rendering the table rows you see on the homepage. So specifically its rending the 
```
2024 - In Progress - 2024-01-04 at 1:28:18 p.m. - Edit
2023 - In Progress - 2024-01-02 at 12:28:18 p.m. - View
```
rows you see looking like this :D

2025-03-12 20:52 UTC, ntsummers1 commented on services/ui-src/src/components/sections/homepage/Homepage.jsx
> +  // console.log("Template Link", getFiscalYearTemplateLink());
Removed :D

2025-03-13 13:50 UTC, gmrabian submitted a review, later dismissed
🌟

2025-03-14 17:27 UTC, merged