Convert Title to use hooks
CMSgov/cms-carts-seds pull request #139730
Opened 2024-08-06 03:44 UTC by ntsummers1

### Description

This migrates the Title component. Specifically, this changes the following:

Removes the connect property
Uses hooks to fetch state

### Related ticket(s)

CMDCT-3813

---
### How to test

You'll have to wait for this one 😅. The timeout should trigger and show a countdown before timing out. Everything should work here!

---
### Pre-review checklist

- [x] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [x] I have updated relevant documentation, if necessary
- [x] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
### Pre-merge checklist

#### Review
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

2024-08-13 20:37 UTC, gmrabian requested changes
One issue with proptypes but still works — do you know if the proptypes still apply when not using connect?

2024-08-13 20:37 UTC, gmrabian commented on services/ui-src/src/components/layout/Title.jsx
> -  urlStateName: PropTypes.string,
I think you accidentally deleted `urlStateName` instead of `formYear`

2024-08-14 15:43 UTC, ntsummers1 commented on services/ui-src/src/components/layout/Title.jsx
> -  urlStateName: PropTypes.string,
You are 100% correct. Good catch!

2024-08-14 15:46 UTC, ntsummers1 commented
> One issue with proptypes but still works — do you know if the proptypes still apply when not using connect?

They do, though it seems they mainly serve as assistance for when you hover over a component. For instance, hovering over the `Title` in the code when referencing the Title Component will show that it takes a prop type of urlStateName which is a string. It doesn't seem to enforce the types though, which begs the question if its truly that helpful or do we remove PropTypes all together and just let native Typescript take control here.

2024-08-15 20:58 UTC, gmrabian approved these changes

2024-08-15 23:24 UTC, britt-mo approved these changes
Tested locally, title appeared as expected

2024-08-16 14:31 UTC, merged