Miscellaneous main branch frontend cleanup
CMSgov/cms-carts-seds pull request #2084
Opened 2022-03-29 15:43 UTC by braxex

# Description

There were several areas of the frontend that needed a bit of cleanup. There's also admittedly more work that can be done, but for now this provides a cleaner baseline to build on.

## How to test

Nothing to really test at this point.

## Dependencies 

Please spell out any dependencies for this change -- ex -- requires an install / update / migration etc

# Get it done

Now that the PR is open this is what happens next

## Code authors checklist
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review 

## Assignee 
- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-03-30 18:33 UTC, gmrabian submitted a review, later dismissed
Code level changes look good to me. I don't know as much about SCSS but this looks like mostly cleanup. I ran locally and worked fine. 

About the linting thing - I read about it a bit. Is the thing we're avoiding just listing a bunch of dependencies in that block?

2022-03-30 23:10 UTC, braxex commented
>About the linting thing - I read about it a bit. Is the thing we're avoiding just listing a bunch of dependencies in that block?

@gmrabian Not exactly. The real issue that's being called out is that the `useEffect` hook has dependencies that are not explicitly listed in that dependency array. That array exists to let the hook know what objects to "watch" (it's not actually "watching" per se but that's another topic), and when any of those declared deps changes, the hook will run again. Declaring all of the dependencies of the code in that hook is helpful because it avoids bugs by ensuring the hook isn't running with stale data. And so we have the `exhaustive-deps` linting rule. But declaring all of the dependencies as the solution often causes more problems. For instance, functions in the hook being referenced in other places, but which also references and update component state (sadly the case with a lot of these). Adding those pieces of state as deps would cause infinite loops. 😕 

There are a few potential fixes, but I kinda want to wait until we have everything hooked back up and running to mess with it any further because I'd hate to think we'd solved them only to find out we've broken some functionality we don't yet understand. Considering the current state of some of these hooks, unexpected side-effects are likely. My hope is sometime toward the end of the year we can circle back to these with a more comprehensive view of what's going on across the repe -- then we can evaluate what the best rewrites/solutions will look like. 🤷

2022-04-01 18:51 UTC, gmrabian approved these changes

2022-04-04 13:13 UTC, BearHanded requested changes

2022-04-04 13:23 UTC, BearHanded approved these changes

2022-04-04 15:13 UTC, merged