MDCT-97: Jest Setup
CMSgov/cms-carts-seds pull request #2189
Opened 2022-04-06 15:35 UTC by karla-vm

# Description

Closes out [MDCT-97](https://qmacbis.atlassian.net/browse/MDCT-97). In this PR, Jest is setup for the `ui-src` directory to start unit testing the frontend. We still don't have any unit tests for the API because we haven't written any endpoints as of yet. However, there is a sample unit test for a frontend component under `services/ui-src/src/__tests__ ` for `UserProfile.js`.

## How to test

- `cd services/ui-src`
- `yarn install`
- `yarn test`

## Dependencies 

Run `yarn install` on your terminal.

# Get it done

We get to write Jest tests!

## Code authors checklist
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review 

## Assignee 
- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-04-06 15:58 UTC, gmrabian approved these changes, later dismissed
lgtm, works locally - remember `nvm use`

2022-04-06 17:26 UTC, karla-vm commented
> lgtm, works locally - remember `nvm use`

Thank you! I added that to the instructions for testing.

2022-04-06 17:31 UTC, bodnarbm requested changes

2022-04-06 17:31 UTC, bodnarbm commented on services/ui-src/package.json
> -    "test": "react-scripts test",
Do we need to change away from `react-scripts test`? react-scripts already uses `jest` as it's test runner. Was there something it was doing that was problematic for us?

2022-04-07 11:17 UTC, karla-vm commented
@braxex can I get a quick set of eyes on this to merge into main?

2022-04-07 11:35 UTC, bodnarbm requested changes
Few changes requests throughout and noted in the comments. Some more global comments are

- The yarn.lock files generated by newer versions of yarn (yarn 2+) are not compatible with yarn 1. Can we please rerun this with a yarn 1.
- We will want to remove the [.yarn/install-state.gz](https://github.com/CMSgov/cms-carts-seds/pull/2189/files#diff-08726f0f086814efdbc11017d6e0102b08abac2d45d6078d359ca189d5989462) from the changes.
- I believe the pattern being followed in qmr and mcr is for tests to live next to the component they are testing. Thus, I think we should move all the files out from under `__test__` and instead place them next to each component. See https://github.com/CMSgov/cms-mdct-qmr/blob/4bc8235f873eb7b25c35db6922d94f36da8488da/services/ui-src/src/components/Header/index.test.tsx as an example

2022-04-07 11:35 UTC, bodnarbm commented on services/ui-src/src/__tests__/UserProfile.test.js
> +import "../setupTests";
We actually want to do this in the jest config itself, to ensure this is ran with every test.

It would be something like

```
"setupFilesAfterEnv": [
      "<rootDir>/src/setupTests.js"
    ],
```

2022-04-07 11:35 UTC, bodnarbm commented on services/ui-src/src/__tests__/DateRange.test.js
> +// TODO: Update testing suite with DynamoDB endpoint (currently points to PostgreSQL endpoint)
Can you explain more about this todo? None of the unit tests should actually hit the endpoint so this should not matter for component tests.

If this is because of `window.env.API_POSTGRES_URL` not being set at all, that can be handled by adding something like

```
global.window.env = {
  API_POSTGRES_URL: "fakeurl",
};
```
in the setupTest.js file.

2022-04-07 11:35 UTC, bodnarbm commented on services/ui-src/src/__tests__/DateRange.test.js
> +/*
Let's make sure we add an issue to fix all these tests. Don't want them to be forgotten about later.

2022-04-07 14:44 UTC, bodnarbm approved these changes, later dismissed
LGTM. Minor nit on gitignore.

2022-04-07 14:44 UTC, bodnarbm commented on .gitignore
> +.yarn/cache/
nit: maybe remove this line?

2022-04-07 14:45 UTC, bodnarbm commented on services/ui-src/babel.config.js
> +          chrome: "67",
We want want to target lower versions of Chrome though as users may not be on the latest.

2022-04-07 14:47 UTC, gmrabian commented on services/ui-src/babel.config.js
> +          chrome: "67",
ah that makes sense. Thanks

2022-04-07 14:52 UTC, karla-vm commented on .gitignore
> +.yarn/cache/
I missed that one! Removed it in the latest commit.

2022-04-07 14:53 UTC, gmrabian approved these changes

2022-04-07 14:56 UTC, bodnarbm approved these changes

2022-04-07 14:57 UTC, merged