MDCT-157: CARTS Table Regularity Master
CMSgov/cms-carts-seds pull request #2200
Opened 2022-04-08 17:04 UTC by juliuscaesar

# Description

[MDCT-157 Carts Table Regularity Master](https://qmacbis.atlassian.net/browse/MDCT-157)

Adds default values when a table header or cell is blank. For table headers the value is `Type` and table cells the value is `No data`.

## How to test

Click through a draft report and ensure that no table has a blank header or cell. Some tables to check are in Section 3C and Section 5.

## Dependencies 

None.

# Get it done

2 Reviews and a merge :upside_down_face: 

## Code authors checklist
- [x] I have performed a self-review of my code
- [x] (Will do this for main) ~~I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)~~
- [x] ~~Necessary analytics were added, or no new analytics were required~~
- [x] ~~I have made corresponding changes to the documentation~~
- [x] I have assigned the PR to myself

## Reviewers Checklist (Two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review 

## Assignee 
- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-04-08 17:15 UTC, gmrabian commented on frontend/react/src/components/fields/SynthesizedTable.js
> +                      : "No data"}
On line 53 is uses "Not Available". Is "No data" preferable? Just wondering if they should be the same, one way or another.

2022-04-08 19:35 UTC, juliuscaesar commented on frontend/react/src/components/fields/SynthesizedTable.js
> +                      : "No data"}
No we decided to keep "Not Available" where it currently exists and add "Not Answered" for all other cases. Just pushed a commit changing "No data" to "Not Answered"

2022-04-08 21:47 UTC, braxex commented
@juliuscaesar Is this in final state ready to be reviewed now?

2022-04-10 00:27 UTC, juliuscaesar commented
@braxex yes

2022-04-11 15:50 UTC, braxex requested changes

2022-04-11 15:59 UTC, juliuscaesar commented on frontend/react/src/components/fields/SynthesizedTable.js
> +                  <td key={index}>
Thank you. We can definitely keep a note of this for when we do this in main.

2022-04-11 16:04 UTC, juliuscaesar commented on frontend/react/src/components/fields/SynthesizedTable.js
> +                      : "Not Answered"}
That results in an empty cell value when `cell.contents == ""`.

2022-04-11 16:31 UTC, braxex commented on frontend/react/src/components/fields/SynthesizedTable.js
> +                      : "Not Answered"}
Hmm... that's weird -- it shouldn't. Got time to pair on it today? Maybe something weird is going on.

2022-04-11 17:55 UTC, braxex commented on frontend/react/src/components/fields/SynthesizedTable.js
> +      if (typeof value.contents === "number" && Number.isNaN(value.contents)) {
Either one of these checks will do the job for you on it's own, so can remove one.

2022-04-11 17:58 UTC, braxex commented on frontend/react/src/components/fields/SynthesizedTable.js
> +      }
Don't need this else here since if it returns higher up it won't reach it.
```suggestion
        return value;
```

2022-04-11 17:58 UTC, braxex commented on frontend/react/src/components/fields/SynthesizedTable.js
> +      } else if (!value.contents) {
Is this second in case the first value is `0`?

2022-04-11 20:53 UTC, braxex approved these changes
What a ride.

2022-04-11 21:11 UTC, gmrabian commented on frontend/react/src/components/fields/SynthesizedTable.js
> +const SynthesizedTable = ({ headers, rows }) => {
Does this affect other files that use this element where question is passed?
I'm just making sure changing this input doesn't affect stuff
Ex: Fieldset.js

```
case "synthesized_table":
      return <SynthesizedTable question={question} {...props} />;
```

2022-04-11 21:25 UTC, juliuscaesar commented on frontend/react/src/components/fields/SynthesizedTable.js
> +const SynthesizedTable = ({ headers, rows }) => {
It's still being passed to the `SynthesizedTable` component but since we pull out `headers` and `rows` from `question` in `mapStateToProps` and use those instead in the component, we don't need to declare that variable there anymore.

2022-04-12 13:31 UTC, gmrabian approved these changes

2022-04-12 13:32 UTC, merged