Db snapshot
CMSgov/cms-carts-seds pull request #2272
Opened 2022-04-22 14:22 UTC by gmrabian

# Description

Added a snapshot identifier attribute so that we can create the DB in the new AWS env from a snapshot.
- The attribute will only apply in the new account
- The attribute can be removed after the initial creation with no change to the DB ([Terraform changelog](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3320-march-12-2021), [Specific terraform pr](https://github.com/hashicorp/terraform-provider-aws/pull/18013/files))
- The snapshot id is passed as a variable since we will make use of it only once

Also put deletion protection (update in place, no interruption) on the db for the existing environment and the new environment

## How to test

- `brew install tfenv` (if you've already installed terraform with homebrew you may need to run `brew unlink terraform` for this to work. No need to relink after -> tfenv handles it all)
- `tfenv install 1.0.11`
- `tfenv use 1.0.11`
- `cd data/aws`
- export AWS credentials for mdct-carts-dev
- `terraform init`
- `terraform workspace list`
- `terraform workspace new {name}` (name just needs to be unique in case multiple people are trying this (although there could be other issues like snapshot availability and resource overlap 🤔 (but that would only matter if you actually apply it, not just plan(which is kinda what the test is going for but nbd if you just plan(planning is good(I used to be someone who planned a lot(lately I just wing it(not sure what happened but I actually think it suits me better(I worry a lot less this way)))))))))
- `terraform workspace select {name}`
- `terraform plan -var application_version=dev-iampath -var vpc_name=mdct-carts-east-dev` (the vars here will be different depending on the AWS environment. These are for mdct-carts-dev regardless of workspace)
- IF YOU WISH TO CREATE RESOURCES FOR _THE REAL TEST_ ™️ 
- `terraform apply -var application_version=dev-iampath -var vpc_name=mdct-carts-east-dev` (this'll take 10-20 minutes for the DB)
- Once above completes, go to postgres.tf and comment out the snapshot_identifier line
- `terraform plan -var application_version=dev-iampath -var vpc_name=mdct-carts-east-dev` If this tells you that there are no changes, then we are good :)

Want to dive deeper? You can ***just run plan*** against the existing AWS env

- export AWS credentials for MACPro
- `terraform init`
- `terraform workspace list`
- `terraform workspace select master`
- `terraform plan -var application_version=master -var vpc_name=macpro-dev`

Make sure db only has deletion-protection update with no recreate!

Wow 😮 ! Wasn't that fun?!

Reach out for help at any time! Especially if you are unsure about what you are creating! You can bug Brandon too :) 

## Dependencies 

tfenv, as listed in instructions

## Code authors checklist
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review 

## Assignee 
- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-04-22 16:56 UTC, bodnarbm commented on data/aws/postgres.tf
> -
nit: add back spacing.

2022-04-22 17:22 UTC, bodnarbm commented on data/aws/postgres.tf
> +  deletion_protection             = terraform.workspace == "prod" || terraform.workspace == "master" || terraform.workspace == "staging"  ? "true" : "false"
Could also think above moving the `terraform.workspace == "prod" || terraform.workspace == "master" || terraform.workspace == "staging"` to a local also since it is reused here in this file, with some name like `is_persistent_workspace` or something like that.

2022-04-22 17:22 UTC, bodnarbm commented on data/aws/variables.tf
> +variable "new_env_snapshot_id" {
could we name this something like `restore_snapshot_id` or `postgres_restore_snapshot_id`. As this is valuable to keep around after the migration in case we ever need to recreate / restore the database.

2022-04-22 17:22 UTC, bodnarbm commented on data/aws/variables.tf
> +}
Lets also add a `type` constraint of `string` and maybe a `description` talking about what this variable controls / does (that it is for setting the source snapshot for the postgres database).

2022-04-22 17:22 UTC, bodnarbm commented on data/aws/variables.tf
> +
Let's set the `default = null`. That will allow this to run normally without the snapshot id being set, but also allow use to set either the -var option or a `TF_VAR_` environment varible to trigger the database creation from the snapshot.

2022-04-22 17:23 UTC, bodnarbm requested changes
Overall this looks great. Just some minor cleanup items I think.

2022-04-22 17:24 UTC, bodnarbm commented on data/aws/variables.tf
> +
Sorry my github VS code extension must have done something weird. This comment was to apply to the default below, for the new variable.

2022-04-25 17:32 UTC, braxex approved these changes
lgtm

2022-04-25 21:02 UTC, karla-vm approved these changes
Ran locally and my DB is up on AWS :)

2022-04-25 21:04 UTC, gmrabian commented
Thanks for the reviews! I'll just get @bodnarbm final say before merging once he is back

2022-04-26 12:40 UTC, bodnarbm approved these changes
LGTM. Ship it!

2022-04-26 12:42 UTC, merged