DynamoDB Best Practices and Unit Tests
CMSgov/cms-carts-seds pull request #2321
Opened 2022-04-29 19:18 UTC by juliuscaesar

# Description

Quick PR for DynamoDB best practices and unit tests.

Changes:
* Uses `query` instead of `scan` for the `section` endpoints
* Updates the `section` unit tests accordingly
* Adds unit tests for `state status`

## Code authors checklist

- [x] I have performed a self-review of my code
- [x] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [x] Necessary analytics were added, or no new analytics were required
- [x] I have made corresponding changes to the documentation
- [x] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-04-29 19:35 UTC, gmrabian approved these changes, later dismissed
Tests passing. I don't know much about scan but I like the use of query - that's what I've usually seen on the backend. 

Nice work!

2022-04-29 19:47 UTC, bodnarbm requested changes
Just some minor items on the get section query.

2022-04-29 19:47 UTC, bodnarbm commented on .github/workflows/pre-commit.yml
> +      - name: Prepare for Jest (backend)
non-blocking: not for this PR but on my mind because of this: We may want to start splitting up some of these steps into separate jobs within the same workflow, to allow taking advantage of parallelism as these tests become a bit slower.

2022-04-29 19:47 UTC, bodnarbm commented on services/app-api/handlers/section/get.ts
> +      KeyConditionExpression: "pk = :pk AND sectionId >= :sectionId",
blocking question: Doesn't the javascript api allow you to specify only the partition key and just not specify the sort key at all?

Something like

``` typescript
KeyConditionExpression: "pk = :pk",
ExpressionAttributeValues: {
  ":pk": `${state}-${year}`,
},
```

2022-04-29 19:47 UTC, bodnarbm commented on services/app-api/handlers/section/get.ts
> +    const queryValue = await dynamoDb.query(params);
This is probably not going to happen with our number of sections and the expected size, but since the query can return more than one response, best practice would be the check if there is another page (check if there is a `LastEvaluatedKey` in the require value) and then handle the other pages if they exist (here I assume we would just retrieve them all).

2022-04-29 19:50 UTC, juliuscaesar commented on services/app-api/handlers/section/get.ts
> +    const queryValue = await dynamoDb.query(params);
I recalled getting an error back there being a mismatch in the key schema but it seems to be working without it now. Just pushed an update.

2022-04-29 19:50 UTC, juliuscaesar commented on services/app-api/handlers/section/get.ts
> +      KeyConditionExpression: "pk = :pk AND sectionId >= :sectionId",
I recalled getting an error back there being a mismatch in the key schema but it seems to be working without it now. Just pushed an update.

2022-05-02 12:46 UTC, bodnarbm commented on services/app-api/handlers/section/get.ts
> +    const queryValue = await dynamoDb.query(params);
Changing this to non-blocking as the current section sizes look to be about 250-260KB and we can handle the additional paging later.

2022-05-02 12:47 UTC, bodnarbm approved these changes

2022-05-02 14:48 UTC, gmrabian approved these changes
I like the parallelism

2022-05-02 14:50 UTC, merged