MDCT-235: Add Program Type to UI and DynamoDB
CMSgov/cms-carts-seds pull request #2330
Opened 2022-05-03 14:46 UTC by karla-vm

# Description

Closes [MDCT-235](https://qmacbis.atlassian.net/browse/MDCT-235). The Program Type field wasn't being pulled into the UI from the database and it was causing the CARTS form questions to not load. 

## How to test

**Check the Frontend**

`./dev local`

Go to `localhost:3000` and log in as State User, verify that Section 1 of the CARTS form is loading!

**Check the DB**

`DYNAMO_ENDPOINT=http://localhost:8000 dynamodb-admin` in a new terminal window

Go to `localhost:8000` and view `local-state-status`, it should have a column for `programType`

## Dependencies

N/A

# Get it done

N/A

## Code authors checklist

- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-05-03 15:51 UTC, BearHanded requested changes

2022-05-03 15:51 UTC, BearHanded commented on services/ui-src/src/util/shouldDisplay.js
> +    program = state.reportStatus[reportStatusCode].programType;
I think this might only work for state users, not co/bo/admin roles

2022-05-03 15:51 UTC, BearHanded commented on services/ui-src/src/actions/initial.js
> +            programType: record.programType,
We probably need to seed this in the db for local testing right now.

Adding a unit test on the api side to make sure this prop comes back couldn't hurt either.

2022-05-03 19:54 UTC, juliuscaesar approved these changes

2022-05-03 20:00 UTC, gmrabian approved these changes
lgtm - verified locally

2022-05-04 19:49 UTC, BearHanded approved these changes

2022-05-04 19:51 UTC, merged