MDCT-223: Fix Dead Spots in Header Menu (main)
CMSgov/cms-carts-seds pull request #2351
Opened 2022-05-06 17:21 UTC by karla-vm

# Description

Same as `master`. 

Closes [MDCT-223](https://qmacbis.atlassian.net/browse/MDCT-223). Users have trouble finding the clickable area of the CARTS header drop-down menu. Now it should be clickable all-around. Also, changed Helpdesk to Contact Us based on Design's suggestion.

## How to test

Populate `.env` files in root and **ui-src**.

`nvm use`
`./dev local`

Navigate to `localhost:3000` and log in as any user type. On the top-right, verify that the menu items are clickable.

## Dependencies

N/A

# Get it done

Clicks!

## Code authors checklist

- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-05-06 17:22 UTC, juliuscaesar submitted a review, later dismissed

2022-05-06 17:25 UTC, juliuscaesar submitted a review, later dismissed

2022-05-06 17:54 UTC, juliuscaesar submitted a review, later dismissed

2022-05-08 17:02 UTC, braxex approved these changes, later dismissed
LGTM. Nothing blocking here. When I originally saw the email about this PR and it said 300 files had been changed I was like 😱  so seeing only 5 after the rebase was 😌 . Nice work. 👍 

Another emoji for fun 🍣

2022-05-08 17:02 UTC, braxex commented on services/ui-src/src/styles/_overrides.scss
> +  padding: 0 ($padding * 2.5) 0 0;
Just curious - what's the reasoning behind using calculated values for these instead of like `1. 25rem` (assuming a rem value of 16px)? Not necessarily a bad thing -- just questioning the pattern.

2022-05-09 12:52 UTC, karla-vm commented on services/ui-src/src/styles/_overrides.scss
> +  padding: 0 ($padding * 2.5) 0 0;
I actually don't know what the reasoning was behind that, the rest of the styling is being done that way so I followed suit, but if there's a better way to do it for `main`, I'd love to learn about it!

2022-05-09 15:27 UTC, braxex requested changes
This looks really good and fixes up those dead spots. In addition to that, I would suggest making the click areas the same for each of the menu options. You can see a couple of the issues in this image: 
![Screen Shot 2022-05-09 at 10 19 52](https://user-images.githubusercontent.com/27705928/167442774-fbae6f91-c705-4604-9559-8c238f83fc75.png)
1. Manage Account eats into Contact Us a bit.
2. Manage Account has a slightly smaller box than the others. Probably needs to be aligned the same.
3. Log Out has an extra area to the left. 
4. There's a _tiny_ (1px) deadzone between the user email and the drop down arrow icon. 

The fix for some of these will entail making the clickable area a parent element. I would suggest making the clickable area for each of the menu items the same, as well as expanding the menu slightly so there's room to align all the icons and the wording. I'm happy to pair on this with you anytime -- just hit me up. 👍

2022-05-11 23:55 UTC, braxex approved these changes, later dismissed
Looking really nice. I added just a couple suggestions, but after those are implemented it's good to go! 👍

2022-05-11 23:55 UTC, braxex commented on services/ui-src/src/styles/_header.scss
>              left: 0;
Because the icons are slightly different sizes, the `padding-right` pushes the labels just a tiny bit out of alignment. This (when applied to all three) will fix that. I've made the same suggestion on the other two.
```suggestion
            display: inline-block;
            width: 16px;
```

2022-05-11 23:55 UTC, braxex commented on services/ui-src/src/styles/_header.scss
>              left: 0;
```suggestion
            display: inline-block;
            width: 16px;
```

2022-05-11 23:55 UTC, braxex commented on services/ui-src/src/styles/_header.scss
>              left: 0;
```suggestion
            display: inline-block;
            width: 16px;
```

2022-05-11 23:55 UTC, braxex commented on services/ui-src/src/styles/_header.scss
> +          padding-right: ($padding * 3);
I noticed that when you click this menu the tabbed focus styles change the background color to white. That makes sense if you have dark text, but if you light text on a dark background like this it kinda does the opposite of accessibility. Slightly changing that tabbed focus style will fix it up. 

Note: I've made a similar suggestion for the menu options below.
```suggestion
        a {
          &:focus {
            background-color: initial;
          }
          padding-right: ($padding * 3);
```

2022-05-11 23:55 UTC, braxex commented on services/ui-src/src/styles/_header.scss
> +      .contact-us {
Same as the suggestion above re: tabbed focus styling.
```suggestion
      a, button {
        &:focus {
          background-color: initial;
        }
      }
      .contact-us {
```

2022-05-12 14:17 UTC, juliuscaesar approved these changes

2022-05-12 14:26 UTC, BearHanded approved these changes

2022-05-12 14:29 UTC, merged