508 pdf
CMSgov/cms-carts-seds pull request #2375
Opened 2022-05-10 20:38 UTC by 13bfrancis

# Description

This is the first go round of making a 508c PDF for CARTS. There are various changes in here that address issues that were found using the accessibility checker in adobe acrobat.

## How to test

This can be tested by viewing a state form, clicking the print button, and then entire form. And then clicking the print button on the new tab that gets opened. After receiving the generated PDF it can then be ran against the accessibility checker for adobe acrobat.

## Code authors checklist

- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-05-10 20:43 UTC, benjaminpaige commented on frontend/react/src/components/fields/CMSLegend.js
> +  console.log({ questionType });
can prob remove this

2022-05-10 20:45 UTC, benjaminpaige commented on frontend/react/src/components/fields/Checkbox.js
> +          key={props.name + "-" + value + "-" + idx}
we could prob interp this if we wanted to clean it up. no biggie either way

2022-05-10 20:46 UTC, benjaminpaige commented on frontend/react/src/components/fields/Question.js
> +  console.log({ question });
.

2022-05-10 20:46 UTC, benjaminpaige commented on frontend/react/src/components/fields/Radio.js
> +// import { Choice } from "@cmsgov/design-system-core";
.

2022-05-10 20:48 UTC, benjaminpaige commented on frontend/react/src/components/layout/Part.js
> +        <h3 className="h4-pdf-bookmark">
maybe update the classname?

2022-05-10 20:48 UTC, benjaminpaige commented on frontend/react/src/components/layout/Section.js
> +        </h2> */}
.

2022-05-10 20:50 UTC, benjaminpaige commented on frontend/react/src/components/fields/CMSLegend.js
> +      </p>
```suggestion
      <div>
        {!hideNumber && <p>{labelBits}</p>}
        {!questionType.includes("text") && <p>{label}</p>}
        {hint && (
          <div className="ds-c-field__hint">
            <Text>{hint}</Text>
          </div>
        )}
      </div>
```

maybe?

2022-05-10 21:30 UTC, TheDanMiller commented on frontend/react/src/components/fields/Checkbox.js
> +          key={props.name + "-" + value + "-" + idx}
<img width="903" alt="image" src="https://user-images.githubusercontent.com/7631428/167725135-aa2215d9-4b1d-405a-bdde-e48beda08a1b.png">
It looks lie code climate picks it up in two places as repeated code

2022-05-16 17:31 UTC, benjaminpaige commented on frontend/react/src/components/fields/Checkbox.js
> +            id={props.name + "-" + value}
```suggestion
            id={`${props.name} -${value}`}
```

2022-05-16 17:46 UTC, benjaminpaige approved these changes

2022-05-17 19:33 UTC, BearHanded requested changes

2022-05-17 19:33 UTC, BearHanded commented on frontend/react/src/components/fields/Radio.js
> +        onClick={unCheck}
Do we need to be firing both these onChange and onClicks in an input component? It looks like it clears and sets its contents back to back.

2022-05-17 19:33 UTC, BearHanded commented on frontend/react/src/components/fields/SynthesizedTable.js
> +  console.log({ question });
Remove log

2022-05-17 19:33 UTC, BearHanded commented on frontend/react/src/components/layout/UploadComponent.js
> +    console.log({ question: this.props.question });
Remove log

2022-05-23 20:49 UTC, 13bfrancis commented on frontend/react/src/components/fields/Radio.js
> +        onClick={unCheck}
I'm not sure. In looking at master it looks like this same logic existed so maybe we can leave it for now. I agree though, that it does seem strange.

2022-05-24 20:06 UTC, BearHanded approved these changes

2022-05-24 21:53 UTC, merged