Backend JSON structure documentation
CMSgov/cms-carts-seds pull request #242
Opened 2020-07-28 09:25 UTC by tadhg-ohiggins

Need things be complex?
Apparently yes, for forms;
Let's try some structure.

Documentation for the backend JSON structure, and the JSON for Section 1 and Section 2b.
Address #240.

2020-07-28 09:27 UTC, tadhg-ohiggins commented
It wasn't immediately evident to me how to get this link to see the documentation in a reasonable format, so: https://github.com/18F/cms-carts-seds/blob/backend-json-structure-docs/docs/backend-json-structure-documentation.rst

2020-07-31 16:56 UTC, cannandev requested changes

2020-07-31 16:56 UTC, cannandev commented on docs/backend-json-section-3.json
> +                            "text": "Have you changed your outreach methods in the last federal fiscal year?",
Can we change this property from `text` to `label`?

2020-07-31 16:56 UTC, cannandev commented on docs/backend-json-section-3.json
> +                            },
Can we add a flag if this question has previous year data? 
```
"entry": null,
"previous_year": true
```

2020-07-31 16:56 UTC, cannandev commented on docs/backend-json-section-3.json
> +            "id": "2020-03-a",
Add a the page url for this subsection? We would use this for routing in the main navigation.
```
"route": "section/3d",
```

2020-08-02 01:17 UTC, tadhg-ohiggins commented on docs/backend-json-section-2.json
> +    "title": "Program Fees and Policy Changes",
Fixed that, good catch.

2020-08-02 01:17 UTC, tadhg-ohiggins commented on docs/backend-json-section-3.json
> +                            "text": "Have you changed your outreach methods in the last federal fiscal year?",
Done.

2020-08-02 01:18 UTC, tadhg-ohiggins commented on docs/backend-json-section-3.json
> +                            },
I added `display_prior_year_data` as an allowed property in `context_data` in the schema, but I haven't added the actual indications about whether or not prior year's data should be displayed to the JSON data.

2020-08-02 01:19 UTC, tadhg-ohiggins commented on docs/backend-json-section-3.json
> +            "id": "2020-03-a",
I'm unwilling to put routing in the data… if it ends up being really awkward not to, we can revisit this.

2020-08-02 01:20 UTC, tadhg-ohiggins commented
@cannandev I addressed the comments, and also made lots of other updates. I think this is good to go, feel free to merge it.

2020-08-03 13:21 UTC, jgillis1 approved these changes

2020-08-03 14:33 UTC, cannandev approved these changes

2020-08-03 14:33 UTC, merged