Feature/choice list refactor
CMSgov/cms-carts-seds pull request #247
Opened 2020-07-28 16:51 UTC by TGriesemer

Possible "issue" is the "hint" element on some choices. Look at Section3A P1_Q2

2020-07-28 19:53 UTC, cannandev requested changes

2020-07-28 19:53 UTC, cannandev commented on frontend/react/src/components/review/Section3C/Questions3C.js
> +                defaultChecked={this.props.previousEntry === "true" ? (this.state.previous_p1_q1 === "yes" ? true : false) : false}
If all we need is a **truthy** or **falsey** value, use the logical operator `&&` instead of a conditional. It reduces the amount of code and gets the same result: 
```
defaultChecked={this.props.previousEntry === "true" && this.state.previous_p1_q1 === "yes"}
```

2020-07-28 19:53 UTC, cannandev commented on frontend/react/src/components/review/Section3C/Questions3C.js
> +              defaultChecked={this.props.previousYear === "true" ? (this.state.previous_p1_q2__2 === "no" ? true : false) : false}
See above note about using logic `&&` operator.

2020-07-28 19:53 UTC, cannandev commented on frontend/react/src/components/review/Section3C/Questions3C.js
> +              {//<ChoiceList hint="Note: This question may not apply to Medicaid Expansion states."/>
Is this line meant to be a comment or the `ChoiceList` component? 

If a comment, react comments don't recognize `//`. They're written as `{/* comment here */}`. That said, we should avoid commenting out code for the sake of removing it. Let's rely on version control. 

If the `<ChoiceList>`, it should wrap around the `<Choice>` components. Right now, this line renders the commented text after the Yes option.

2020-07-28 19:53 UTC, cannandev commented on frontend/react/src/components/sections/section2a/Section2A.js
> +      ly_p2_q2: "",//From choiceList refactor
Let's put comments like this in the commit comments, not in code.

2020-07-28 19:53 UTC, cannandev commented on frontend/react/src/components/sections/basicInfo/questions/QuestionsBasicInfo.js
> +        defaultChecked={this.props.previousYear === "true" ? (this.state.previous_programType === "sCHIP" ? true : false) : false}
See above note about using logic && operator.

2020-07-28 19:53 UTC, cannandev commented on frontend/react/src/components/sections/section3a/questions/Questions3A.js
> +                      defaultChecked={this.props.previousEntry === "true" ? (this.state.previous_p1_q1 === "yes" ? true : false) : false}
See above note about using logic && operator.

2020-07-28 19:53 UTC, cannandev commented on frontend/react/src/components/sections/section3c/questions/Questions3C.js
> +                defaultChecked={this.props.previousEntry === "true" ? (this.state.previous_p1_q2__2 === "no" ? true : false) : false}
See above note about using logic && operator.

2020-07-28 19:53 UTC, cannandev commented on frontend/react/src/components/review/Section3C/Questions3C.js
> +import { TextField, ChoiceList, Choice } from "@cmsgov/design-system-core";
If we're not calling `ChoiceList` in this file, it should be removed from imports.

2020-07-30 13:38 UTC, jgillis1 commented on frontend/react/src/components/sections/section2a/Section2A.js
> +      ly_p2_q2: "",//From choiceList refactor
This isn't needed on this page. Removed.

2020-07-30 13:46 UTC, jgillis1 commented
@cannandev Requested changes have been made. Please review at your convenience.

2020-07-30 17:56 UTC, cannandev approved these changes

2020-07-30 18:02 UTC, merged