MDCT-192: Uncertify CARTS Report (Modal Dialog)
CMSgov/cms-carts-seds pull request #2482
Opened 2022-05-17 20:32 UTC by karla-vm

# Description

Closes [MDCT-192](https://qmacbis.atlassian.net/browse/MDCT-192). An approver can now click on `Uncertify` to uncertify a report using a dialog that will pop up and ask that user to confirm.

## How to test

`./dev local`

Log in as Admin (functionally, an Approver) and click `Uncertify` for one of the reports. The following should happen:

- A modal dialog magically appears
- You are able to close the dialog using the magical **Close** button on the top-right
- If you click on **Yes, Uncertify Report**, the page magically reloads
- Upon reload, the report status has changed to "In Progress" ... magically

One more _magically_ for good measure 🪄 

## Dependencies

N/A

# Get it done

Now that the PR is open this is what happens next

## Code authors checklist

- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-05-18 14:15 UTC, gmrabian commented on services/app-api/handlers/apiNames.txt
> +POST /uncertify_report/{year}/{state} - uncertifies the report for a given state and year
I think you can reuse the `POST /state_status/{year}/{state}` endpoint rather than make a new one. The purpose of that endpoint is to update the status of a report, so you can just pass in the status you want. Then you don't have to make new files just for this use case.

Let me know if I'm missing some context here and we can discuss! Either way I think we can design this api a bit better

2022-05-18 14:16 UTC, gmrabian commented on services/app-api/libs/authorization.ts
>  };
There's probably a better way to handle this

2022-05-18 14:59 UTC, braxex requested changes
I have the same questions on the API design -- I know Brendan has been working on some auth patterns for the API in general -- might be good to get his input when he's back to make sure we're being consistent.

2022-05-18 19:03 UTC, karla-vm commented on services/ui-src/src/styles/_main.scss
> +    }
Done-zo!

2022-05-18 19:04 UTC, karla-vm commented on services/app-api/libs/authorization.ts
> +  //const requestMethod = event.httpMethod as RequestMethods;
It wasn't being used, forgot to un-comment :)

2022-05-18 19:05 UTC, karla-vm commented on services/app-api/libs/authorization.ts
>  };
@BearHanded was working on a better handling for this, since we're introducing a new user (Approver), we can wait on this while he's on vacation.

2022-05-23 12:37 UTC, BearHanded commented on services/app-api/handlers/stateStatus/update.ts
> +          username: username,
The username on the report shouldn't change here, should it? In my mind it should still be attributed to the original user who submitted it.

2022-05-23 12:40 UTC, BearHanded commented on services/app-api/libs/authorization.ts
>  };
I'm at least implementing this change on my side if not further refactoring. The above code is originates from QMR where all non-get methods are blocked for anyone but state users. We don't have that same requirement, and will likely need to move any further auth logic into the responsibilities of the handler, unless there's a clean way to rig it up elsewhere

2022-05-23 19:46 UTC, BearHanded approved these changes

2022-05-23 23:10 UTC, braxex approved these changes
Per conversations with team, addressing further auth work in follow-up PR.

2022-05-24 12:15 UTC, merged