Implement Sticky Footer
CMSgov/cms-carts-seds pull request #2483
Opened 2022-05-18 19:23 UTC by ntsummers1

# Description

Takes the footer and makes it sticky! It'll now stay put to the bottom of the page whether theres content above it or not. I would love any feedback on any naming conventions or if you would have implemented this differently. 

Heres an example of where you can see it stick to the bottom:

![stickyfooter](https://user-images.githubusercontent.com/19439679/169139209-377b5c36-812b-4472-80db-02af2cd028e7.png)

## How to test

Simply go to any page that contains the footer and you'll be able to see it in action! A specific page to look at though is the [user/profile](http://localhost:3000/user/profile) page

## Dependencies

N/A

# Get it done

Now that the PR is open this is what happens next

## Code authors checklist

- [x] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [x] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-05-18 21:44 UTC, braxex commented on services/ui-src/src/AppRoutes.js
> +        <Spinner />
```suggestion
      {VisibleHeader}
      <div className="app-content">
        <Spinner />
```

2022-05-18 21:45 UTC, braxex requested changes
Just a note about moving the header. Otherwise looking good.

2022-05-19 14:19 UTC, karla-vm submitted a review, later dismissed
Looks awesome, Nick! 🎉  I agree with Brax's comment about the Header being outside of the app, but otherwise everything makes sense.

2022-05-19 14:48 UTC, karla-vm approved these changes

2022-05-19 15:03 UTC, braxex approved these changes

2022-05-19 15:32 UTC, merged