MDCT-252: Help Desk User View All CARTS Reports
CMSgov/cms-carts-seds pull request #2562
Opened 2022-05-19 19:52 UTC by karla-vm

# Description

Closes [MDCT-252](https://qmacbis.atlassian.net/browse/MDCT-252). The new Help Desk user (functionally, an admin user) can view a list of all CARTS reports. These reports are now sorted by year, then alphabetically. For example:

`2022 Alabama`
`2022 Alaska`
`2022 California`
`2021 Alaska`
`2020 California`

Also, the "List Users", "Add Users", and "Generate Form Base Templates" buttons should be _gone_.

## How to test

`./dev local`

Log in as an admin user, check out how everything is sorted and those buttons don't exist anymore!

## Dependencies

N/A

# Get it done

N/A

## Code authors checklist

- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-05-19 20:25 UTC, gmrabian approved these changes, later dismissed
works! excellent added:deleted line ratio

2022-05-20 12:39 UTC, bodnarbm commented on services/ui-src/src/components/sections/homepage/CMSHomepage.js
>                    .sort((a, b) => (a.lastChanged > b.lastChanged ? -1 : 1))
This last sort would resort everything based on the last time the data was changed regardless of the year and state code and should be removed.

2022-05-20 12:49 UTC, bodnarbm requested changes
In addition to the sort changes noted, @karla-vm, can you check when logging in as a user with the help desk role (like `george@test.com`). I believe the Home component currently routes help desk users to an unauthorized page.

2022-05-20 12:49 UTC, bodnarbm commented on services/ui-src/src/components/sections/homepage/CMSHomepage.js
> +                  .sort((a, b) => (a.stateCode < b.stateCode ? -1 : 1))
Is the sort intended to be by full state name or the state's code?

We display the state name to the user, so I believe the sort by state should be based on that. For example, for Alabama and Alaska, if we sort by name, Alabama comes first, but if we sort by state code, Alaska comes first.

2022-05-20 12:49 UTC, bodnarbm commented on services/ui-src/src/components/sections/homepage/CMSHomepage.js
>                    .sort((a, b) => (a.lastChanged > b.lastChanged ? -1 : 1))
This last sort would resort everything based on the last time the data was changed regardless of the year and state code and should be removed.

2022-05-20 12:49 UTC, bodnarbm commented on services/ui-src/src/components/sections/homepage/CMSHomepage.js
> +                  .sort((a, b) => (a.year > b.year ? -1 : 1))
I think it may cause confusion later on to have this done via multiple sorts, as the reader of the code needs to remember that the the latest sort wins over the prior sorts and that browsers (from 2019 and later) have had stable sorts (which is the reason why we know that within a given year here that its sorted by the state information). My suggestion would be to do a single sort with a sort comparison function that first checks if they years differ and then returns based the year order, and if the years are the same then returns based on the state information.

Something like

```
# puesdocode
a, b:
  if a.year != b.year
    return comparison value based on year

  return comparison value based on state 
```

2022-05-21 01:00 UTC, bodnarbm approved these changes
Thanks!

2022-05-23 14:22 UTC, gmrabian approved these changes

2022-05-23 14:54 UTC, merged