Update header with new 'reportING' treatment
CMSgov/cms-carts-seds pull request #2917
Opened 2022-06-13 20:06 UTC by ntsummers1

# Description

Per Kim: "Hey y'all, we need to update CARTS branding, Stephanie just said it should be "CHIP Annual Reporting Template System"."

## How to test

`./dev local`
Check if the header has the new reporting image!

## Dependencies

Please spell out any dependencies for this change -- ex -- requires an install / update / migration etc

# Get it done

Now that the PR is open this is what happens next

## Code authors checklist

- [x] I have performed a self-review of my code
- [x] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [x] Necessary analytics were added, or no new analytics were required
- [x] I have made corresponding changes to the documentation
- [x] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-06-13 20:17 UTC, BearHanded submitted a review, later dismissed

2022-06-13 20:17 UTC, gmrabian requested changes
I see a handful of other places this needs to be changed, like the Homepage. I suggest doing a quick search of the repo and updating those while you're at it

2022-06-14 14:30 UTC, gmrabian approved these changes
Looks good!

2022-06-14 14:49 UTC, braxex approved these changes

2022-06-14 15:14 UTC, merged