Mdct 296 seeding
CMSgov/cms-carts-seds pull request #3116
Opened 2022-06-17 14:29 UTC by karla-vm

# Description

Closes [MDCT-296](https://qmacbis.atlassian.net/browse/MDCT-296). The `/state` endpoint should return FMAP and ACS data from the DB to load and populate Section 2 (Part 2) and Section 5 (Table 3) of CARTS reports.

## How to test

* Run locally `./dev local`
* Sign in to CARTS
* Open up a state report and navigate to **Section 2**
* Ensure the table in **Part 2: Number of Uninsured Children in Your State** is populated with either data or 'Not Available' (there should be no empty rows)
* Navigate to **Section 5**
* Ensure the _eFMAP_ row in **Table 3: Federal and State Shares** is populated with either data or 'Not Available' (there should be no empty rows)

Enjoy! 🪄 

## Dependencies

N/A

# Get it done

Cool things.

## Code authors checklist

- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-06-17 17:47 UTC, gmrabian submitted a review, later dismissed
LGTM!

2022-06-17 18:51 UTC, gmrabian commented on services/app-api/handlers/state/tests/get.test.ts
> +  __esModule: true,
technically don't need `__esModule` here or on convertToDynamoExpressionVars. Only need it where you're mocking a default export, like with dynamodb-lib above :)

2022-06-17 19:34 UTC, gmrabian commented on services/app-api/handlers/state/tests/get.test.ts
> +  __esModule: true,
can delete this one too :)

2022-06-17 19:53 UTC, gmrabian approved these changes, later dismissed
Lovely! Just need codeclimate to play nice

2022-06-17 19:54 UTC, karla-vm commented
> Lovely! Just need codeclimate to play nice

If only 😭

2022-06-21 15:24 UTC, BearHanded requested changes
Can we make the acs & fmap data their own tables? It might make updating that info less complicated in the long run when in X years a team is asked to update or add to the data set.

2022-06-29 17:00 UTC, BearHanded approved these changes

2022-06-29 17:25 UTC, gmrabian approved these changes
lgtm!

2022-06-30 12:35 UTC, merged