MDCT-355: Remove CMS User note
CMSgov/cms-carts-seds pull request #3137
Opened 2022-06-22 15:19 UTC by ntsummers1

# Description

Fixes [MDCT-355](https://qmacbis.atlassian.net/browse/MDCT-355)

Hated seeing the CMS User note? So did the rest of the world. It's done, kapeesh? It won't be bothering us no more. 

![Screen Shot 2022-06-22 at 11 17 19 AM](https://user-images.githubusercontent.com/19439679/175067404-c0a2642d-3a09-4cdb-a222-efae16830a60.png)

## How to test

./dev local
Log in
See that the main page is filled with only the most effective wording now known to man.

## Dependencies

# Get it done

Now that the PR is open this is what happens next

## Code authors checklist

- [x] I have performed a self-review of my code
- [x] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [x] Necessary analytics were added, or no new analytics were required
- [x] I have made corresponding changes to the documentation
- [x] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-06-22 17:27 UTC, BearHanded commented on services/ui-src/src/components/sections/homepage/CMSHomepage.js
> -              <div className="edit-info">CMS user</div>
There's a blurb like this on the other homepages as well for their relevant role. They get modified by my current PR as well. Do they need to get pulled out? They say Help Desk & CMS Admin

2022-06-24 14:23 UTC, ntsummers1 commented on services/ui-src/src/components/sections/homepage/CMSHomepage.js
> -              <div className="edit-info">CMS user</div>
Per David its allllllll got to go. Update now made.

2022-06-24 17:07 UTC, BearHanded requested changes

2022-06-24 17:09 UTC, BearHanded approved these changes
Thanks for the quick update!

2022-06-27 15:12 UTC, gmrabian approved these changes
looks good

2022-06-27 15:14 UTC, merged