508 pdf (#2375)
CMSgov/cms-carts-seds pull request #3166
Opened 2022-06-27 20:04 UTC by jdinh8124

# Description
Resolves:
https://qmacbis.atlassian.net/jira/software/c/projects/MDCT/boards/229?modal=detail&selectedIssue=MDCT-325
- Pulls in this commit from v2: https://github.com/CMSgov/cms-carts-seds/commit/3e4651b6b19107909e0b61b79cb53d15fee2d7b9

## Code authors checklist

- [x] I have performed a self-review of my code
- [x] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-06-28 15:27 UTC, BearHanded requested changes
noticed some rendering oddities here, going back and double checking the PR against master as well

2022-06-28 15:27 UTC, BearHanded commented on services/ui-src/src/components/fields/SynthesizedTable.js
> -const SynthesizedTable = ({ question, rows }) => {
Pulled this down and ran locally, I notice that the tables that are missing data (data for this is coming in another branch that has an open PR) are displaying without headers.
Table in branch
![image](https://user-images.githubusercontent.com/6362494/176216632-6f575c4a-d790-4760-9130-ab3aca2acc34.png)


Table in main:
![image](https://user-images.githubusercontent.com/6362494/176216060-570108ea-9060-4700-afee-3ca042e0a180.png)

Section 2: Part 2.

It should still probably render the headers and formatting

2022-06-28 15:27 UTC, BearHanded commented on services/ui-src/src/components/layout/Subsection.js
>      <div id={subsectionId}>
Most questions are rendering twice now in section 3c.
![image](https://user-images.githubusercontent.com/6362494/176217305-60f880dd-f83c-470f-a841-a43349770c1e.png)

this may impact the other branch as well, double checking

2022-06-29 16:56 UTC, BearHanded approved these changes

2022-06-30 21:49 UTC, gmrabian approved these changes

2022-07-01 14:18 UTC, merged