Build section3A with dynamic data
CMSgov/cms-carts-seds pull request #324
Opened 2020-08-07 15:48 UTC by andrewadcock

Section3a is built out using the current JSON. This does not include support for "Copy from Last Year" or Answers from last year

2020-08-10 16:15 UTC, cannandev requested changes

2020-08-10 16:15 UTC, cannandev commented on frontend/react/src/components/sections/section3Aapi/questions/Questions3AApi.js
> +                        <textarea
Why text `<textarea>` and not the `<Textfield>` component?
If type `text_short`, pass `size="short"` to <Textfield>, etc.
See https://design.cms.gov/components/text-field/

2020-08-10 16:15 UTC, cannandev commented on frontend/react/src/components/sections/section3Aapi/questions/Questions3AApi.js
> +                          value={question.answer.entry}
FYI,  `value` prop on `textarea` should not be null. Consider using an empty string to clear the component if `{question.answer.entry}` is null. It would look like `question.answer.entry || ''`

But using the `<Textfield>` component should take care of this.

2020-08-10 16:15 UTC, cannandev commented on frontend/react/src/components/sections/section3Aapi/questions/Questions3AApi.js
> +                    ) : null}
Let's use logical operators (**&&**, **||**) instead of ternary when we only have one return. Instead of returning `null` if the condition is false:
`{condition && truthyStatement}`
`{question.type === "ranges" && (<FPL label={question.label}) />)}`

2020-08-10 16:15 UTC, cannandev commented on frontend/react/src/components/sections/section3Aapi/questions/Questions3AApi.js
> +                                conditional={question.conditional}
Not showing children when Yes is clicked.

2020-08-10 19:24 UTC, andrewadcock commented on frontend/react/src/components/sections/section3Aapi/questions/Questions3AApi.js
> +                                conditional={question.conditional}
This is now unneeded and has been removed. The child questions won't show until the changes from #325 get merged. Once that is done, I'll request a re-review.

2020-08-11 12:29 UTC, andrewadcock commented on frontend/react/src/components/sections/section3Aapi/questions/Questions3AApi.js
> +        {/* {Data.section.subsections.map((subsections) => ( */}
Removed debug code.

2020-08-11 15:15 UTC, andrewadcock commented on frontend/react/src/components/sections/section3Aapi/questions/Questions3AApi.js
> +    let valueFromParent;
Removed

2020-08-11 15:16 UTC, andrewadcock commented on frontend/react/src/components/sections/section3Aapi/questions/Questions3AApi.js
> +                          value={question.answer.entry}
Updated to use textfield and resolve to an empty string instead of null

2020-08-11 15:17 UTC, andrewadcock commented on frontend/react/src/components/sections/section3Aapi/questions/Questions3AApi.js
> +                        <textarea
Converted to TextField component

2020-08-11 15:17 UTC, andrewadcock commented on frontend/react/src/components/sections/section3Aapi/questions/Questions3AApi.js
> +                    ) : null}
Alternate logic has been added

2020-08-11 15:18 UTC, andrewadcock commented on frontend/react/src/components/sections/section3Aapi/questions/Questions3AApi.js
> +                                name={question.id}
Key property added with value of index

2020-08-11 15:29 UTC, cannandev approved these changes

2020-08-11 15:29 UTC, merged