Remove percentage as a fieldset_type option, instead make it an actio…
CMSgov/cms-carts-seds pull request #335
Opened 2020-08-11 05:47 UTC by tadhg-ohiggins

Demote percentage—
It is now a mere action.
These docs are fluid.

Remove `percentage` as a `fieldset_type` option, instead make it an `action` for `synthesized_value` (and by extension `synthesized_table`). Add example showing its use.

2020-08-12 08:45 UTC, cannandev requested changes

2020-08-12 08:45 UTC, cannandev commented on docs/section-schemas/backend-json-section-3.json
> +                            "type": "checkbox_flag",
I left a comment in the google doc about the location of the checkbox. From an accessibility standpoint, it should belong to part 4, not question 1. I'd like to move it outside of the question fieldset. I propose two ways to handle this:
id: `2020-03-c-04-a`, which wouldn't conflict with numbering for the inputs that follow. 
**or** 
id: `2020-03-c-04-01` and continue with that sequence for the rest of the structures that follow, but we have an additional `marker` property that we'll use to number each question instead of the `id`

2020-08-12 08:45 UTC, cannandev commented on docs/section-schemas/backend-json-section-3.json
> +                          "skip_text": "1a omitted because you indicated that you have the age range breakdown data available.",
Do we need to show this text? The user won't notice the missing fields once they check the checkbox.

2020-08-12 08:45 UTC, cannandev commented on docs/section-schemas/backend-json-section-3.json
> +                    "fieldset_type": "marked",
Instead of marked/unmarked, I propose an `input_grid` structure with the following properties:
```
            id="2020-03-c-04-04"
            title="July - September of 2020 (18 months later)"
            label="How many children were no longer enrolled in CHIP six months later?"
            hint=["Possible reasons for no longer being enrolled","Transferred to another health insurance program other than CHIP","Didn’t meet eligibility criteria anymore","Didn’t complete documentation","Didn’t pay a premium or enrollment fee"]
            isChild="false" />
```
```
            id=2020-03-c-04-04-a`
            title=""
            label="How many children were no longer enrolled in CHIP but were enrolled in Medicaid six months later?"
            hint=""
            isChild="true" 
```
I'd also love a `marker` property that just said `4` or `4a`, to avoid substring-ing the id, but that might be asking too much.

`isChild` would let us style this question differently - in this case, indented from 4. Note that from a structural standpoint, there is no parent-child relationship allowed with this structure.

2020-08-12 09:14 UTC, cannandev requested changes

2020-08-12 09:14 UTC, cannandev commented on docs/section-schemas/backend-json-section-3.json
> +                "label": "January – March 2020 (12 months later)",
We need a flag that this section should be inactive and filled out next year.

2020-08-12 09:14 UTC, cannandev commented on docs/section-schemas/backend-json-section-3.json
> +                "label": "July – September 2020 (18 months later)",
We need a flag that this section should be inactive and filled out next year.

2020-08-12 16:49 UTC, tadhg-ohiggins commented on docs/section-schemas/backend-json-section-3.json
> +                        "type": "question",
The `type: question` part was a stray, but this should be `integer`; the answer can't be anything but a whole number.

2020-08-12 16:53 UTC, tadhg-ohiggins commented on docs/section-schemas/backend-json-section-3.json
> +                            "type": "checkbox_flag",
We can move it, we just have to decide to where, based on the comments in the doc. I'm not in favor of adding a `marker` property. To move this checkbox question I'd keep it in an `unmarked_descendants` `fieldset` because that will flag that it shouldn't have a marker and shouldn't alter the markers of questions after it.

2020-08-12 16:55 UTC, tadhg-ohiggins commented on docs/section-schemas/backend-json-section-3.json
> +                          "skip_text": "1a omitted because you indicated that you have the age range breakdown data available.",
Depends on whether we're showing the labels, and on whether or not e.g. 3 has a subquestion. If it does, its label will be 3f, and so in order to have things make sense to the user we need to let them know why we're skipping to `f`.

2020-08-12 16:56 UTC, tadhg-ohiggins commented on docs/section-schemas/backend-json-section-3.json
> +                    "fieldset_type": "marked",
I don't think I understand how this would work. I do think that `input_grid` wouldn't solve the problems that `marked`/`unmarked_descendants` tackle.

2020-08-12 16:58 UTC, tadhg-ohiggins commented on docs/section-schemas/backend-json-section-3.json
> +                "label": "January – March 2020 (12 months later)",
I left that out because I wasn't sure yet how to handle it; I don't think that consideration should hold up the PR.

2020-08-14 02:44 UTC, cannandev commented on docs/section-schemas/backend-json-section-3.json
> +                          "skip_text": "1a omitted because you indicated that you have the age range breakdown data available.",
Marking this issue `Resolved` since we decided 3a will be 4, etc. No subquestion.

2020-08-17 13:43 UTC, cannandev approved these changes

2020-08-17 13:43 UTC, merged