Okta auth 2
CMSgov/cms-carts-seds pull request #337
Opened 2020-08-11 15:02 UTC by sethsacher

2020-08-11 15:03 UTC, sethsacher commented
Replaces https://github.com/18F/cms-carts-seds/pull/334

2020-08-11 21:08 UTC, tadhg-ohiggins approved these changes

2020-08-12 07:05 UTC, cannandev requested changes

2020-08-12 07:05 UTC, cannandev commented on frontend/react/src/App.js
> +    <Router>
😊  glad you're using Router

2020-08-12 12:44 UTC, sethsacher commented on frontend/react/src/Home.js
> +    window.location.pathname.split("/")[1] === "reports" ? null : <Header />;
I didn't add this - it was just moved over from App.js into this new Home.js component. @jgillis1 should review in a separate PR.

2020-08-12 12:45 UTC, sethsacher commented on frontend/react/src/components/layout/Logout.js
> +const issuer = 'https://${yourOktaDomain}/oauth2/default';
Whoops this shouldn't be there at all, it's carry over from a template I used. I'll remove it.

2020-08-12 12:47 UTC, sethsacher commented on frontend/react/src/auth-config.js
> +  };
@cannandev do you suggest a new line here as well?

2020-08-12 12:55 UTC, sethsacher commented
Okta-based authentication wrapping the entire CARTS React frontend. If a user is not authenticated, they will be directed to the default CMS Okta login screen. After providing valid credentials, the user is directed to the CARTS homepage. This is currently only implemented for local development, and only for the frontend. Additional checks should be implemented on the Django backend to ensure an unauthenticated user cannot access an API endpoint.

Logout was added as well. This is configured to route the user back to root, which will then redirect to the default CMS Okta login screen per the auth workflow.

To authenticate, a user must exist in the Okta application "MACPRO SPA". I have admin privileges right now and can add users for you, and you will likely want to request admin privileges from the Okta team to manage this moving forward. This integration applies authentication to a local build. You'll either want to follow up with code to apply auth only to certain environments, or add users to the MACPRO SPA app in order to login appropriately. Let me know if you have any questions about how to configure additional environments (this will require adding the new environment URL to Okta, and possibly creating the MACPRO SPA Okta app in higher Okta environments).

We plan to generalize the auth code in a reusable component across MACPRO Apps. I'll follow up with the team at a later date if/when that becomes a reality.

2020-08-12 14:17 UTC, jgillis1 commented on frontend/react/src/Home.js
> +    window.location.pathname.split("/")[1] === "reports" ? null : <Header />;
I agree. We can address this through another Issue/PR.

2020-08-12 14:51 UTC, cannandev commented on frontend/react/src/auth-config.js
> +  };
yes. thanks!

2020-08-12 16:37 UTC, cannandev approved these changes

2020-08-12 16:37 UTC, merged