MDCT-307: Security Updates from macpro-quickstart
CMSgov/cms-carts-seds pull request #3615
Opened 2022-08-09 20:42 UTC by karla-vm

# Description

Closes [MDCT-1843](https://qmacbis.atlassian.net/browse/MDCT-1843).

Based on two security updates to the `macpro-quickstart` repository, the following changes were replicated to `CARTS v3`.

- This [PR](https://github.com/CMSgov/macpro-quickstart-serverless/pull/556) describes the first mitigation, which is to fix the command injection vulnerability in the `avScan` Lambda function.

- This [PR](https://github.com/CMSgov/macpro-quickstart-serverless/pull/239) describes the second mitigation, which is to add code scanning to the codebase using `CodeQL` (one more "code" for good measure... code).

## How to test

Run locally and ensure everything works exactly the same as before!

## Dependencies

N/A

# Get it done

N/A 
## Code authors checklist

- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-08-09 21:17 UTC, gmrabian requested changes, later dismissed
The avscan failed when I tried to upload a file to this bucket. See suggested change for more detail

<img width="860" alt="Screen Shot 2022-08-09 at 2 17 20 PM" src="https://user-images.githubusercontent.com/57802560/183763170-645885fe-e5f5-4c98-a164-4256af4e1703.png">

2022-08-09 21:18 UTC, gmrabian commented on services/uploads/src/clamav.js
> +      `-d ${pathToFile}`,
```suggestion
      `-d /tmp/ ${pathToFile}`,
```

2022-08-09 21:19 UTC, gmrabian commented on services/uploads/src/clamav.js
> +      `-d ${pathToFile}`,
This part from the old version didn't get carried over. MCR needed the same thing to work properly. Hopefully this fixes it!

2022-08-09 21:32 UTC, gmrabian commented
I don't think the codeql file got checked in 😅

2022-08-09 21:39 UTC, gmrabian commented
My last note! I added to the JIRA ticket to say `CARTS will want to pay special attention to the changes to places where a user uploads files. If not already implemented, be sure to use an approval list like they have, where only certain name formats and file extensions are allowed`. Don't we have upload locations here? Are we able to make use of that part of the quickstart PR as well? Or is it not there yet. Just checking this got seen!

2022-08-09 22:29 UTC, karla-vm commented on services/uploads/src/clamav.js
> +      `-d ${pathToFile}`,
Thank you!!

2022-08-09 22:30 UTC, karla-vm commented
> My last note! I added to the JIRA ticket to say `CARTS will want to pay special attention to the changes to places where a user uploads files. If not already implemented, be sure to use an approval list like they have, where only certain name formats and file extensions are allowed`. Don't we have upload locations here? Are we able to make use of that part of the quickstart PR as well? Or is it not there yet. Just checking this got seen!

CARTS v3 does have uploads, I will take a look at that part and make sure we're covered.

2022-08-10 14:11 UTC, gmrabian commented on .github/workflows/codeql-analysis.yml
> +      - master
Change this one and the one above to main!

2022-08-10 14:12 UTC, gmrabian commented on .github/workflows/codeql-analysis.yml
> +        uses: github/codeql-action/analyze@v1
This step and the one on line 32 are on v2 now. We should use that because v1 will deprecate in a few months.

2022-08-10 14:17 UTC, gmrabian commented
> The avscan failed when I tried to upload a file to this bucket. See suggested change for more detail
> 
> <img alt="Screen Shot 2022-08-09 at 2 17 20 PM" width="860" src="https://user-images.githubusercontent.com/57802560/183763170-645885fe-e5f5-4c98-a164-4256af4e1703.png">

@karla-vm I'm actually seeing this error on main too so maybe that'll have to be a separate bug

2022-08-10 17:02 UTC, gmrabian commented
Oh yeah you can also add a codeql badge to the readme!

2022-08-10 21:12 UTC, gmrabian commented on .github/workflows/codeql-analysis.yml
> +        uses: github/codeql-action/init@v1
```suggestion
        uses: github/codeql-action/init@v2
```

2022-08-10 21:15 UTC, gmrabian commented on services/uploads/src/antivirus.js
> +async function isS3FileNameValid(s3ObjectKey) {
I'm not sure you need this here since you're replacing the name of the file with a random string for the purposes of this scan. I think it makes more sense to put it in the ui-src code where the upload takes place. That way you can alert the user if they need to change the name.

2022-08-11 17:28 UTC, gmrabian submitted a review, later dismissed
Looks good! After you merge maybe create a bug ticket for the virus scan failing issue. I know we fixed it in MCR at one point so there's gotta be a PR in there somewhere

2022-08-15 14:19 UTC, BearHanded requested changes

2022-08-15 14:19 UTC, BearHanded commented on services/ui-src/src/hooks/authHooks/userProvider.js
> -    window.location.origin.includes("dt4brcxdimpa0.cloudfront.net"); // TODO: remove once v3 is at the former address
we need to keep dt4brcxdimpa0.cloudfront.net around until we shift over to mdctcarts.cms.gov

2022-08-17 15:57 UTC, BearHanded commented on services/ui-src/src/hooks/authHooks/userProvider.js
> +    window.location.origin.includes("dt4brcxdimpa0.cloudfront.net");
Can we handle this with equality the same way you handled the other condition?

2022-08-17 17:02 UTC, BearHanded approved these changes

2022-08-17 19:09 UTC, TheDanMiller approved these changes

2022-08-17 19:10 UTC, merged