content updates
CMSgov/cms-carts-seds pull request #3823
Opened 2022-09-26 21:04 UTC by scwambach

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context.

## How to test

The more detail here the better on how to test

## Dependencies

Please spell out any dependencies for this change -- ex -- requires an install / update / migration etc

# Get it done

Now that the PR is open this is what happens next

## Code authors checklist

- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-09-26 21:05 UTC, gmrabian submitted a review, later dismissed

2022-09-26 22:49 UTC, BearHanded requested changes
This also needs the section two change from the ticket:
https://qmacbis.atlassian.net/browse/MDCT-1988

2022-09-27 16:26 UTC, BearHanded approved these changes

2022-09-27 20:01 UTC, karla-vm commented on services/ui-src/src/store/formData.js
>          // Added mid year as a quick fix for 2021 forms see: https://qmacbis.atlassian.net/browse/OY2-12744 Should be removed ASAP!!
I think this comment is outdated, we should be able to remove it! @BearHanded correct me if I'm wrong.

2022-09-27 20:01 UTC, karla-vm approved these changes

2022-09-27 20:39 UTC, gmrabian approved these changes
🤷

2022-09-28 00:42 UTC, merged