2021 acs seed data
CMSgov/cms-carts-seds pull request #3826
Opened 2022-09-27 20:06 UTC by scwambach

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context.

## How to test

The more detail here the better on how to test

## Dependencies

Please spell out any dependencies for this change -- ex -- requires an install / update / migration etc

# Get it done

Now that the PR is open this is what happens next

## Code authors checklist

- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [ ] Necessary analytics were added, or no new analytics were required
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

2022-09-27 20:27 UTC, BearHanded approved these changes

2022-09-28 12:52 UTC, karla-vm approved these changes

2022-09-28 12:53 UTC, karla-vm approved these changes

2022-09-28 13:11 UTC, BearHanded requested changes
Double checked this in a deployed env and it is pulling in the wrong numbers when you view a state. There's a bug somewhere in that code. Let's pair up on this and try to knock it out

2022-09-28 13:36 UTC, BearHanded approved these changes
have the fix in a separate branche

2022-09-28 13:36 UTC, merged