Revert "Revert "Okta auth 2""
CMSgov/cms-carts-seds pull request #389
Opened 2020-08-20 14:56 UTC by jgillis1

Reverts 18F/cms-carts-seds#341

2020-08-24 16:50 UTC, cannandev requested changes

2020-08-24 16:50 UTC, cannandev commented on frontend/react/src/App.js
> +      {/* <Security {...config.oidc}>
Default: Show `<Security/>`, hide `<Route component={Home}/>`
Flag present: Hide `<Security/>`, show `<Route component={Home}/>`

2020-08-24 16:50 UTC, cannandev commented on frontend/react/src/components/layout/Header.js
> +                      {/* OKTA Enabled */}
Default: Show `<Logout/>`
Flag present: Hide `<Logout/>`

2020-08-24 16:50 UTC, cannandev commented on frontend/react/src/App.js
> +To Enable OKTA Authentication, you will need to:
Instead of enabling/disabling by commenting out code, let's add a url parameter like `?okta_disabled=true`
Okta auth should be on by default and skipped in the presence of the flag.

2020-08-31 15:59 UTC, cannandev reviewed
@jgillis1 Did the Okta folks confirm that client IDs were public? I can't remember.

2020-09-15 15:56 UTC, mgwalker commented
Is this PR still valid? #526 and #535 also enabled Okta with a bypass mechanism, but I don't know if it covered everything that's in this PR.

2020-09-15 15:59 UTC, closed without merging