Feature/temporary share link
CMSgov/cms-carts-seds pull request #403
Opened 2020-08-24 09:18 UTC by cannandev

React component for generating, reviewing and revoking a new shared link. 

### Share View (seen by Data SME) 

- Create route for share view (seen by Data SME) at `/shared/:uuid`
- Hitting Submit dispatches `UNDER_REVIEW` action.
- Add informational text at top
- Add submit link at top and bottom
- Hide other routes, navigation/global links
- Add dialogue box that confirms submitting/thank you
- Send user to No Access page 

### Share Link and Modal (seen by Data Centralizer)

- Remove old Share Progress toggle 
- Click Generate button dispatches `CREATE_SHARE_LINK` to store. 
- Click Revoke button dispatches `EXPIRE_SHARE_LINK` to store. 

Related to #402

2020-08-24 18:52 UTC, mgwalker requested changes
This seems fine, but with one question/fix about the conditional for whether to show the side nav.

2020-08-24 18:52 UTC, mgwalker commented on frontend/react/src/reactRouter.js
> +    window.location.pathname.split("/")[1] === ("reports" && "shared") ? null : (
What does this conditional do? Reading it, I would expect it to end up being the same as:

```js
window.location.pathname.split("/")[1] === "shared"
```

because the `("reports" && "shared")` would be evaluated to just `"shared"`. Is that the intent?

2020-08-25 16:57 UTC, cannandev commented on frontend/react/src/reactRouter.js
> +    window.location.pathname.split("/")[1] === ("reports" && "shared") ? null : (
That was the intent. Rewrote to explicitly say that, instead of trying to be fancy.

2020-08-27 15:51 UTC, mgwalker approved these changes

2020-09-09 14:46 UTC, mgwalker commented
When I joined the project I didn't realize approvers were supposed to merge, so I didn't merge this PR... 😬  Should we still merge it now that we're punting on share links for the initial release? Or would it be better to close it and put a link to it in the issue so we don't lose track of the work for the future? (Just trying to clean up the PR list and I accidentally left this one lingering...)

2020-09-15 15:53 UTC, mgwalker commented
Going to close this PR, but will link to it in the associated issue so the work isn't lost for the future.

2020-09-15 15:53 UTC, closed without merging