Dev s3
CMSgov/cms-carts-seds pull request #451
Opened 2020-08-27 20:49 UTC by joeaero19

PLEASE **_DO NOT_** MERGE IMMEDIATELY!!!

2020-08-28 01:38 UTC, dwhitecl commented on frontend/react/Dockerfile
> +<<<<<<< HEAD
looks like youve got a conflict here

2020-08-31 16:10 UTC, joeaero19 commented on frontend/react/Dockerfile
> +<<<<<<< HEAD
I resolved this conflict by taking out the entire dockerfile. It is no longer needed.

2020-09-03 18:45 UTC, mdial89f requested changes

2020-09-03 18:45 UTC, mdial89f commented on .jenkins/Jenkinsfile.dev
> +
Can you remove this new line

2020-09-03 18:45 UTC, mdial89f commented on .jenkins/Jenkinsfile.dev
> +
Can you remove this new line

2020-09-03 18:45 UTC, mdial89f commented on .jenkins/Jenkinsfile.dev
> +
Can you remove this new line

2020-09-03 18:45 UTC, mdial89f commented on .jenkins/Jenkinsfile.dev
> +
Can you remove this new line

2020-09-03 18:45 UTC, mdial89f commented on .jenkins/Jenkinsfile.dev
>      stage("Deploy Data Layer") {
Can you remove this new line

2020-09-03 18:45 UTC, mdial89f commented on .jenkins/Jenkinsfile.dev
>      stage("Deploy Data Layer") {
iw sa copy/pasting this on new lines haha it seemed aggresive.  if you can clean up the new lines, sweet.

2020-09-03 18:45 UTC, mdial89f commented on .jenkins/Jenkinsfile.master
> +           tar -zcvf cartsbuild.tar.gz build
The logic to copy env.sh and .env must exist here too:

        # copy .env and env.sh into the archive so we can use them after we unzip
        cp env.sh build/env.sh
        cp .env build/.env

2020-09-03 18:45 UTC, mdial89f commented on .jenkins/Jenkinsfile.master
> +           tar -zcvf cartsbuild.tar.gz build
needs to be there before you tar it up

2020-09-03 18:45 UTC, mdial89f commented on .jenkins/Jenkinsfile.master
> +               aws s3 sync build s3://${S3_BUCKET_NAME}
The logic to populate env-config.js with the right urls must happen before the sync

               #Populate the static archive with the API_POSTGRES_URL and the API_SQLSERVER_URL before you sync it to the host bucket

              cd build  && ./env.sh  && cd ..

2020-09-03 18:45 UTC, mdial89f commented on .jenkins/Jenkinsfile.prod
> +               aws s3 sync build s3://${S3_BUCKET_NAME}
ditto as above... have to substitute correct urls prior to sync
               #Populate the static archive with the API_POSTGRES_URL and the API_SQLSERVER_URL before you sync it to the host bucket

              cd build  && ./env.sh  && cd ..

2020-09-15 16:44 UTC, mdial89f approved these changes

2020-09-15 16:46 UTC, merged