Add dynamic form buttons (next, prev) to all sections
CMSgov/cms-carts-seds pull request #530
Opened 2020-09-09 18:21 UTC by andrewadcock

Adds dynamic next and previous buttons. Also adds back the share and print buttons and design from #113.

`Share` button is still using dummy data (Covered in #403 )

`All changes auto-saved` button has been moved to a new component and styled.

2020-09-10 18:58 UTC, cannandev commented on frontend/react/src/components/layout/FormNavigation.js
> +const selectSectionsForNav = (state) => {
Can we move this to the `selectors.js`?

2020-09-11 15:53 UTC, andrewadcock commented on frontend/react/src/components/layout/FormNavigation.js
> +const selectSectionsForNav = (state) => {
Successfully moved to selectors.js. Thanks!

2020-09-11 21:12 UTC, mgwalker requested changes
Only blocking change I see is that the browser hard reloads when you click the button, which means there are also a series of roundtrips to the API, reloading the state, etc. I've proposed 3 lines of changes that will use `history.push` instead for a soft navigation that should take care of it.

I had a couple of other questions/comments about how to clean the code up a little, but overall I think this is in good shape. 😄

2020-09-11 21:12 UTC, mgwalker commented on frontend/react/src/components/layout/FormNavigation.js
> +    const { location, sections } = this.props;
```suggestion
    const { history, location, sections } = this.props;
```

Pull in the history object. See the later comment about why!

2020-09-11 21:12 UTC, mgwalker commented on frontend/react/src/components/layout/FormNavigation.js
> +    }
This seems like it's a lot of effort just to derive URLs from IDs. How about something simpler:

```js
const items = [];
sections.forEach(section => {
  section.subsections.forEach(subsection => {
    items.push(idToUrl(subsection.id));
  });
});
```

There might be a little more weirdness to account for sections with a single subsection (where the URL is something like `sections/2020/00/`, for example, but it doesn't make sense to me to have a pair of maps with a nested map when the final output is just these URLs.

2020-09-11 21:12 UTC, mgwalker commented on frontend/react/src/components/layout/FormNavigation.js
> +                  href={previousUrl}
```suggestion
                  onClick={() => { history.push(previousUrl); }}
```

Use the history object to push instead of using an `<a>` (that's how these buttons render if there's a `href` property attached). That way we don't hard-reload the site and instead just do an internal navigation.

2020-09-11 21:12 UTC, mgwalker commented on frontend/react/src/components/layout/FormNavigation.js
> +                  href={nextUrl}
```suggestion
                  onClick={() => { history.push(nextUrl); }}
```

2020-09-14 12:36 UTC, andrewadcock commented on frontend/react/src/components/fields/Autosave.js
> +import React, { Component } from "react";
Got an answer: Keep it in a separate component and we will deal with it later.

2020-09-14 16:32 UTC, mgwalker approved these changes
We need to add an issue to scroll the window back to the top when the user clicks the nav buttons, and make sure we handle focus appropriately when that happens, but this PR is ready to go.

2020-09-14 16:32 UTC, merged