Feature/api 2b
CMSgov/cms-carts-seds pull request #531
Opened 2020-09-09 19:04 UTC by TGriesemer

-Dynamic render from Redux for 2a & 2b
-Writing to redux for both
-Added action type QUESTION_ADDED in intial.js and handling of the type in formData
-Added addElementToFragment to intial.js
-Added synthesized_value type to QuestionComponent (NEEDS REVIEW-no label included in json)
-Added noninteractive_table type to QuestionComponent
-Added ObjectiveAndGoals.js for handling creation of new objective and goal objects

2020-09-09 23:56 UTC, tadhg-ohiggins commented on frontend/react/src/components/sections/section2api/ObjectiveAndGoals.js
> +const addNewGoal = (newGoalId, objectiveId) => {
For both new goals and new objectives, we should pull the data out of the store and repurpose it rather than hardcoding it here. The bottom of this section in the docs https://github.com/18F/cms-carts-seds/blob/master/docs/section-schemas/backend-json-structure-documentation.rst#objectives includes a reference implementation for how to do that.

2020-09-11 18:11 UTC, TGriesemer commented on frontend/react/src/components/sections/section2api/ObjectiveAndGoals.js
> +const addNewGoal = (newGoalId, objectiveId) => {
@tadhg-ohiggins 
The code has been updated so that when you 
-add an objective it copies over and rewrites #1 Objective.
-add a goal it copies over and rewrites #1 Goal from #1 Objective

2020-09-15 19:13 UTC, tonydavydets approved these changes
looks good, great job!

2020-09-15 19:28 UTC, mgwalker requested changes
There are a few places where I think the changed behavior is likely to be a bug, and some changes that we need to make for performance reasons. Overall though, this is a good step forward.

This feels like a very high priority for a refactor as soon as we can breathe, to rearrange code so that this fits into the regular Question Component instead of being its own magic thing. But we can cross that bridge in a few weeks.

2020-09-15 19:58 UTC, TGriesemer commented on frontend/react/src/store/selectors.js
> +  }
As far as I could tell, the original json path did not work for repeatables so I added in something that checked for 2b repeatables. Objectives that met the first part of the if statement were at length 21 so they would not get the new JP assignment. Repeatables are at length 27 so they met both conditions and were given a functioning JP.

2020-09-15 20:02 UTC, TGriesemer commented on frontend/react/src/store/formData.js
> +      return JSON.parse(JSON.stringify(sdata));
Updating the code with your suggestion returns this error. I can declare the fragment outside of the switch statement if you prefer that. 
![image](https://user-images.githubusercontent.com/61795347/93258639-9f568e80-f76c-11ea-9d1d-d244ae9e9543.png)

2020-09-15 21:16 UTC, mgwalker commented on frontend/react/src/store/formData.js
> +      return JSON.parse(JSON.stringify(sdata));
Oops, you're right. It needs brackets. It's [bad practice](https://wiki.sei.cmu.edu/confluence/display/c/DCL41-C.+Do+not+declare+variables+inside+a+switch+statement+before+the+first+case+label) to declare new variables inside a `case` without brackets because the `case` is just a label, so there's *not* scoping – I got it backwards. I think if we had better eslint rules turned on, for example, it'd yell about it. So what you really need is probably something more like:

```js
case QUESTION_ANSWERED:
{
  const fragment = ...
  return ..
}
case QUESTION_ADDED:
{
  const fragment = ...
  return ...
}
```

2020-09-15 21:22 UTC, mgwalker commented on frontend/react/src/store/selectors.js
> +  }
When I tried it using a [27-character question ID](https://mgwalker.github.io/cms-carts-jsonpath/#%24..%5B*%5D.contents.section.subsections%5B*%5D.parts%5B*%5D..questions%5B%3F(%40.id%3D%3D'2020-02-b-01-01-01-02-01-01')%5D), it worked. Also for [a repeatables](https://mgwalker.github.io/cms-carts-jsonpath/#%24..%5B*%5D.contents.section.subsections%5B*%5D.parts%5B*%5D..questions%5B%3F(%40.id%3D%3D'2020-02-b-01-01-01-02')%5D). I'm curious to know what isn't/wasn't working and see if we can hash it out!

2020-09-15 21:49 UTC, mblevins-collabralink commented on frontend/react/src/components/sections/section2api/questions/Questions2Bapi.js
> +    );
I concur on this idea - it's much more object-oriented and you know that makes me warm and fuzzy. It will also be a relief to anyone who has to debug it in the future.

2020-09-16 14:14 UTC, TGriesemer commented on frontend/react/src/components/sections/section2api/objectives/Objective2bApi.js
> +      `2020-02-b-01-01-${objectiveNumber}-02`,
How would you recommend building a self-contained repeatables object? Tadhg said that we should be pulling the first repeatable/objective to create new ones so I tried to take that route but if you have a better suggestion I can update it.

2020-09-16 14:21 UTC, TGriesemer commented on frontend/react/src/components/sections/section2api/questions/Questions2Bapi.js
> +  state: state,
How would you recommend me getting state to ObjectivesAndGoals.js so that I can use the select question and pass it state?

2020-09-16 14:28 UTC, TGriesemer commented on frontend/react/src/components/sections/section2api/questions/Questions2Bapi.js
> +                                  index === 0 ? (
How would you recommend building this so it won't be highly-dependent on the order of the contents of the data? I was thinking that if they added questions it wouldn't be on the same level as an objective.

2020-09-16 14:38 UTC, TGriesemer commented on frontend/react/src/components/fields/QuestionComponent.js
> +              ) : null}
These are the fieldsets that I am working with. If you have a suggestion to what the other conditional should be, I can add it in.
![image](https://user-images.githubusercontent.com/61795347/93352304-b054dd80-f808-11ea-994f-788d61bc5b75.png)

2020-09-16 14:43 UTC, TGriesemer commented on frontend/react/src/components/sections/section2api/ObjectiveAndGoals.js
> +        goal.fieldset_info.targets[1] = `${tempTarget[0]}-${tempTarget[1]}-${tempTarget[2]}-${tempTarget[3]}-${tempTarget[4]}-${objectiveId}-${tempTarget[6]}-${goalIdString}-${tempTarget[8]}`;
I do not see another way to dynamically build the target without assuming that they will always use values within the goal. If there is a synthesized value that is based on other questions, then I think we would have to build a new target builder to handle that case. 

If you have a suggestion as to how it should be built to dynamically so that it handles all possible targets, I can implement that based on your suggestion.

2020-09-16 21:52 UTC, TGriesemer commented on frontend/react/src/store/selectors.js
> +  }
It is working so I removed the if statement

2020-09-16 21:53 UTC, TGriesemer commented on frontend/react/src/store/formData.js
> +      return JSON.parse(JSON.stringify(sdata));
Created fragment outside of the switch.

2020-09-16 21:54 UTC, TGriesemer commented on frontend/react/src/components/sections/section2api/questions/Questions2Bapi.js
> +  state: state,
removed state from this page

2020-09-16 21:56 UTC, TGriesemer commented on frontend/react/src/components/sections/section2api/objectives/Objective2bApi.js
> +      `2020-02-b-01-01-${objectiveNumber}-02`,
The id is now being built from the id of the first objective.

2020-09-16 21:58 UTC, TGriesemer commented on frontend/react/src/components/sections/section2api/questions/Questions2Bapi.js
> +    );
Thanks for the suggestion! I have implemented this and the new code is in initial.js

2020-09-16 21:58 UTC, TGriesemer commented on frontend/react/src/components/sections/section2api/questions/Questions2Bapi.js
> +                                                  .default_entry
I have updated this so the first objective uses default_entry and any other objectives use entry.

2020-09-16 22:00 UTC, TGriesemer commented on frontend/react/src/components/sections/section2api/questions/Questions2Bapi.js
> +                                            />
I have sent a message to Erin, Greg, Tadhg, and Jenna on how to handle the display of any objectives after the first one. I have implemented something but we should note that it should probably be approved by an 18f team member before it is forgotten.

2020-09-16 22:06 UTC, TGriesemer commented on frontend/react/src/components/sections/section2api/objectives/Objective2bApi.js
> +      addNewGoal(newGoalId, objectiveNumber, year, this.props.state)
This has been updated too and moved to initial.js

2020-09-17 16:45 UTC, TGriesemer commented
Note that the conditional in 2b goal question 2 does not function properly

2020-09-24 17:45 UTC, jgillis1 commented
Closing this as the decomposed QuestionComponent provides for Section 2 (old 2a) and Section 4 (old 2b).

2020-09-24 17:45 UTC, closed without merging