Allow for null from API
CMSgov/cms-carts-seds pull request #532
Opened 2020-09-09 19:46 UTC by andrewadcock

2020-09-10 18:32 UTC, cannandev requested changes

2020-09-11 15:37 UTC, andrewadcock commented on frontend/react/src/components/layout/DateRange.js
> +                  this.state["monthStart"] ? this.state["monthStart"] : this.props.question.answer.entry ? this.props.question.answer.entry[0].split("-")[2] : null
I've converted this to a function. I'm doing the calculations in the method for clarity but if you think I should pass the ordinal and index as params, I will refactor.

2020-09-15 12:58 UTC, jgillis1 approved these changes
Claire's concerns have been addressed.

2020-09-15 15:49 UTC, mgwalker approved these changes

2020-09-15 15:51 UTC, merged