WIP: Prev/Next Buttons
CMSgov/cms-carts-seds pull request #601
Opened 2020-09-16 19:04 UTC by andrewadcock

On page load, scroll to top and remove focus from the selected button.

2020-09-16 21:06 UTC, jgillis1 requested changes

2020-09-16 21:06 UTC, jgillis1 commented on frontend/react/src/components/layout/FormNavigation.js
> +    console.log("items-sections", sections);
Remove console.log

2020-09-16 21:06 UTC, jgillis1 commented on frontend/react/src/components/layout/FormNavigation.js
> +    console.log("items", items);
Remove console.log

2020-09-17 15:55 UTC, andrewadcock commented on frontend/react/src/components/layout/FormNavigation.js
> +    console.log("items-sections", sections);
Removed

2020-09-17 15:55 UTC, andrewadcock commented on frontend/react/src/components/layout/FormNavigation.js
> +    console.log("items", items);
Removed

2020-09-17 18:12 UTC, mblevins-collabralink approved these changes
Navigation appears to work correctly.

2020-09-17 18:14 UTC, jgillis1 approved these changes

2020-09-17 18:15 UTC, jgillis1 commented
QA Review has been completed and the PR is ready for 18F review.

2020-09-17 18:53 UTC, tonydavydets approved these changes

2020-09-17 21:09 UTC, mgwalker approved these changes
I love this approach.

I just have a recommendation below that tweaks the `<ScrollToTop>` component so that it doesn't wrap the rest of the app. The main thing is that is shortens the render tree and makes things a tiny bit easier to find in the dev tools. I'm going to approve this because it's fine as-is, but I'm going to leave it unmerged in case you want to make the suggested changes. In either case, feel free to merge it whenever you're ready.

2020-09-17 21:09 UTC, mgwalker commented on frontend/react/src/components/Utils/ScrollToTop.js
> +function ScrollToTop({ history, children }) {
```suggestion
function ScrollToTop({ history }) {
```

2020-09-17 21:09 UTC, mgwalker commented on frontend/react/src/components/Utils/ScrollToTop.js
> +    return <Fragment>{children}</Fragment>;
```suggestion
    return null;
```

2020-09-17 21:09 UTC, mgwalker commented on frontend/react/src/reactRouter.js
> +        <ScrollToTop>
```suggestion
        <ScrollToTop />
```

2020-09-17 21:09 UTC, mgwalker commented on frontend/react/src/reactRouter.js
> +        </ScrollToTop>
```suggestion
```

2020-09-18 13:29 UTC, andrewadcock commented on frontend/react/src/components/Utils/ScrollToTop.js
> +function ScrollToTop({ history, children }) {
Super smart and super clean!

2020-09-18 13:32 UTC, andrewadcock commented
This appears to have stopped working correctly. Related: The vertical nav is displaying duplicates of sections. More investigation is needed.

2020-09-18 13:40 UTC, andrewadcock commented
After a reboot, the nav is working again. Unsure of the issue but it appears to be resolved.

2020-09-18 13:43 UTC, jgillis1 approved these changes

2020-09-18 13:44 UTC, merged