Feature/3i
CMSgov/cms-carts-seds pull request #602
Opened 2020-09-16 19:14 UTC by jgillis1

JSON and Fixtures for Subsection 3i. The front end renders everything but the repeatables, which still needs to be built out. 

Content Doc: https://docs.google.com/document/d/1dRgcKDL7tyGJ3EQuBomhW03xxyeQQ-Hv3eqSNnouutw/edit

Issue #553

2020-09-17 13:13 UTC, andrewadcock reviewed
Looks good. Once the repeatables are built out, this should work fine!

2020-09-17 20:11 UTC, tonydavydets approved these changes

2020-09-17 20:47 UTC, mblevins-collabralink approved these changes

2020-09-17 20:55 UTC, jgillis1 commented
QA Review has been completed and the PR is ready for 18F review.

2020-09-17 22:12 UTC, mgwalker requested changes
Let's talk about the schema change in more detail. Also, please update the schema documentation if you make changes to the schema. (It's the ReStructured Text `backend-json-structure-documentation.rst` file in the `docs/section-schemas` directory.)

2020-09-17 22:12 UTC, mgwalker commented on docs/section-schemas/backend-section.schema.json
> +        },
I'm not comfortable with `text_2` to handle a second paragraph. It has the potential to get out of hand and doesn't scale at all. Two alternatives that come immediately to mind:

1. Add newline characters to the text and use those as paragraph delimiters. When the text is rendered, split it on newlines and then map the pieces to paragraphs.
   ```js
   text.split("\n").map(paragraph => <p>{paragraph}</p>)
   ```
   The upside is that we wouldn't have to change any of our components that use the `text` property – they'd render the newline literally and it'd be a harmless single whitespace. We also wouldn't have to update any other subsection data since it's a convention rather than a schema change.

2. Turn the `text` property into an array. Map the array elements into paragraphs.
   ```js
   text.map(paragraph => <p>{paragraph}</p>
   ``
   The upside to this approach is I think it's more explicit in the data how the text is meant to be rendered. The downside is we'd have to update every existing subsection in the JSON since the schema changed. Alternatively, `text` could be updated so that is *one of* an array of strings or a single string, which just creates a little bit of extra complexity in parsing it.

@tadhg-ohiggins Do you have thoughts or preferences about the best way to handle paragraphs in subsection helper text?

2020-09-17 22:12 UTC, mgwalker commented on frontend/react/src/components/layout/Part.js
> +    state: state,
I addressed this in [#604](https://github.com/18F/cms-carts-seds/pull/604#discussion_r490566765), but I won't rehash it here. I assume it'll get worked out in a rebase/merge later.

2020-09-17 23:20 UTC, jgillis1 commented on docs/section-schemas/backend-section.schema.json
> +        },
Gotcha. So, to clarify, when an existing property doesn't meet the content needs, it's acceptable to modify the property accordingly rather than create a new property?
I think I prefer option 1, personally so I will look into that tomorrow while Tadhg considers them as well.

2020-09-17 23:21 UTC, jgillis1 commented on frontend/react/src/components/layout/Part.js
> +    state: state,
Yes, however it's resolved in #604 will take precedent. I just needed something in this branch to be sure the JSON was complete.

2020-09-18 09:41 UTC, tadhg-ohiggins commented on docs/section-schemas/backend-section.schema.json
> +        },
I prefer the first option since the cases where this is necessary seem to be the minority. If we find later that most question text has newlines, we should switch to an array as a future enhancement.

2020-09-18 09:44 UTC, tadhg-ohiggins commented on docs/section-schemas/backend-section.schema.json
> +        },
Also, either changing or adding properties probably means the issue is worth bringing up for discussion.

2020-09-18 11:37 UTC, mblevins-collabralink commented on docs/section-schemas/backend-section.schema.json
> +        },
I concur that option one is better at this point - and I should have caught this when reviewing it.

2020-09-18 14:09 UTC, mgwalker approved these changes
A minor typo and a question about structuring the data, but nothing I see that's worth holding up the merge!

A question for @erinzstrenio: in the docs, the language is to "skip to the next section" if they answer no to part 1, question 1. I think the implementation here follows the docs, but the upshot is that parts 2 and 3 will both show a skip-text alert if the answer to question 1 is no. Should we create an issue to make it such that there is only one skip-text alert shown? I don't *thing* there's a way in the current JSON schema to hide multiple parts with a single skip-text, but we can investigate.

2020-09-18 16:04 UTC, erinzstrenio commented
@mgwalker We can actually get rid of Part 3 and move that single question from Part 3 to the end of Part 2 to avoid the double skip-text alerts. Does that help? (hopefully didn't make it more complicated?) Just updated the google doc.

2020-09-18 17:11 UTC, mgwalker reviewed
Oops! Forgot to mention these earlier, but for some reason standup brought it back to mind.

2020-09-18 17:11 UTC, mgwalker commented on frontend/react/src/components/layout/Subsection.js
> +const Subsection = ({ partIds, subsectionId, title, text, text_2 }) => {
```suggestion
const Subsection = ({ partIds, subsectionId, title, text }) => {
```

2020-09-18 17:11 UTC, mgwalker commented on frontend/react/src/components/layout/Subsection.js
> +    text_2: subsection ? subsection.text_2 : null,
```suggestion
```

2020-09-18 17:11 UTC, mgwalker commented on frontend/react/src/store/selectors.js
> +      text_2: subsection.text_2,
```suggestion
```

2020-09-18 18:05 UTC, jgillis1 commented on docs/section-schemas/2020-ak-section-3.json
> +        "title": "Health Services Initialtive (HSI) Programs",
Typo has been corrected and the content changes Erin put up on 9/18/2020 have been made.

2020-09-18 18:14 UTC, merged