WIP: Check for conditional when rendering parts
CMSgov/cms-carts-seds pull request #604
Opened 2020-09-16 19:31 UTC by andrewadcock

Previously, parts were only hidden based on programType. This allows parts to check shouldDisplay for parts.

2020-09-16 20:26 UTC, jgillis1 requested changes

2020-09-16 20:26 UTC, jgillis1 commented on frontend/react/src/components/layout/Part.js
> +    state: state,
Is it appropriate to return the full state?

2020-09-17 15:53 UTC, andrewadcock commented on frontend/react/src/components/layout/Part.js
> +    state: state,
It's a requirement for shouldDisplay.

2020-09-17 15:59 UTC, jgillis1 approved these changes

2020-09-17 19:17 UTC, tonydavydets approved these changes

2020-09-17 19:27 UTC, jgillis1 commented
QA Review has been completed and the PR is ready for 18F review.

2020-09-17 21:16 UTC, mgwalker requested changes

2020-09-17 21:16 UTC, mgwalker commented on frontend/react/src/components/layout/Part.js
> +    state: state,
It is not appropriate to return the full state for performance reasons, unfortunately. This will mean that any change anywhere in the state will cause every Part to re-render, which can be expensive.

Instead, you could move the `showPart` check into the `mapStateToProps` and just return a boolean instead of the whole state. E.g.:

```js
const mapStateToProps = (state, { partId }) => {
  const part = selectFragment(state, partId);
  const contextData =  _.has(part, "context_data") ? part.context_data : null;

  return {
    text: part ? part.text : null,
    title: part ? part.title : null,
    context_data: contextData,
    programType: state.stateUser.programType,
    show: showPart(contextData, state.stateUser.programType, state)
};
```

Then in the component, you'd extract `show` from the props and use that as the conditional.

2020-09-18 13:36 UTC, jgillis1 approved these changes

2020-09-18 13:45 UTC, mgwalker approved these changes
Nice

2020-09-18 13:45 UTC, merged