Modularize the question component
CMSgov/cms-carts-seds pull request #621
Opened 2020-09-21 16:55 UTC by mgwalker

When I was working on the input grid component, I was having trouble slotting into the monolithic question component, so I took some time to split it up into modules. This preserves the logic and behavior that was previously implemented in `QuestionComponent`, `CMSChoice`, `CMSRanges`, and `CMSRange`, but restructures it so that it is more dynamic and flexible.

I also added [eslint](https://npm.im/eslint) with Airbnb+prettier rules. It's not enabled globally because that's a big, heavy lift, but I did apply it to the code I was restructuring. As a result, I tweaked some of the code to satisfy the linter.

### Added behavior

- Objectives, goals, and other repeatables work (including Section 2B)
- Synthesized values work
- Synthesized tables work
- Updates the router to be entirely dynamic
- Skip text for hidden questions that contain it (parts were handled previously)

### Known issues

- Section 5 needs to be able to synthesize a value in a more complex way than we currently handle. As a stopgap, the Section 5 JSON includes an invalid target ID, causing it to fail to render. This should be pretty minor to fix.

2020-09-21 17:12 UTC, mgwalker commented on frontend/react/.env
> +SKIP_PREFLIGHT_CHECK=true
create-react-app comes with its own version of eslint. If you install a newer version of your own, the app will refuse to build (in dev only, presumably). It's a little silly. Anyway, this disables the preflight version check so that it'll build in dev and we can keep going.

2020-09-21 17:12 UTC, mgwalker commented on frontend/react/src/components/fields/Autosave.js
> +import React from "react";
For a few of these, I just tweaked them a bit to satisfy the linter. I was running it on this whole `fields` directory.

2020-09-21 17:12 UTC, mgwalker commented on frontend/react/src/components/fields/DateRange.js
> +import React from "react";
This component is just a thin wrapper over the existing `DateRange` component, to basically glue up the two `onChange` function styles.

2020-09-22 17:40 UTC, jgillis1 commented
@mgwalker Would you have time tomorrow or Thursday to meet with the CL team on your changes? We would like to develop a more complete understanding of what has been implemented, why and what, if anything is still outstanding? If a meeting isn't convenient, perhaps you could provide a write up? We want to ensure we are 100% on the same page so we can continue to provide the best possible product to CMS.

2020-09-22 18:24 UTC, mgwalker commented
Yes, I can definitely make time for that! I'll message you on Slack to see if we can find a time, and if there's not a good time, I'll write something up to go into more detail.

2020-09-23 16:49 UTC, jgillis1 requested changes
- [x] `hint={question.hint}` is missing from it looks like all fields/component.js files `{...props}` is not executing it (if that is supposed to do so)

- 3C Table: Denials for First Time Applicants looks good and is calculating nicely

2020-09-23 16:49 UTC, jgillis1 commented on frontend/react/src/components/fields/Radio.js
> +      onChange={onCheck}
We need a disabled property here `disabled={question.answer.readonly}`
Examples: Basic Info Part 1 Q2

2020-09-23 16:49 UTC, jgillis1 commented on frontend/react/src/actions/repeatables.js
> +  });
Again, I'm just really impressed with the simplicity you were able to achieve here.

2020-09-23 16:49 UTC, jgillis1 commented on frontend/react/src/components/fields/Percentage.js
> +      %
The % is displaying on the line below the response. Can we get it on the same line or perhaps in the text box?

2020-09-23 16:49 UTC, jgillis1 commented on frontend/react/src/components/fields/SynthesizedValue.js
> +import React from "react";
This (I believe it's this) is appearing on screen as a disabled text box. Can it not be a text box and just show/not show the value?
Examples: 3C Part 3 Q4 and 3I Part 2 Q5

2020-09-23 16:49 UTC, jgillis1 commented on frontend/react/src/components/fields/Repeatables.js
> +import React from "react";
General question and it may not go here but, when a Repeatable is added, it's not immediately apparent on the screen that anything happened (other than the side scroll bar gets smaller). Is it possible to have the screen focus on the first element of the new Repeatable?

2020-09-23 16:49 UTC, jgillis1 commented on frontend/react/src/components/fields/Objectives.js
> +import React from "react";
Same question here as with repeatables. General question and it may not go here but, when an Objective is added, it's not immediately apparent on the screen that anything happened (other than the side scroll bar gets smaller). Is it possible to have the screen focus on the first element of the new Objective?

2020-09-23 17:28 UTC, mgwalker commented on frontend/react/src/components/fields/Percentage.js
> +      %
I want to spin this into a separate issue. The CMS eAPD app has a percent input type that puts the % inside the textbox, like with the currency text fields. I haven't looked to see how much effort it'd be to port that over to CARTS. Let me take a look, and if it's more than a quick fix, would you be okay with merging this and fixing the percent display separately?

2020-09-23 17:28 UTC, mgwalker commented on frontend/react/src/components/fields/Objectives.js
> +import React from "react";
Hard agree on both of these. We also need to do that for screenreader users anyway.

2020-09-23 18:44 UTC, mgwalker commented on frontend/react/src/components/fields/Percentage.js
> +      %
Never mind, it wasn't that much effort. 😄

2020-09-23 19:59 UTC, tonydavydets reviewed
a slightly cleaner way of making sure an integer less than 10 is preceded by a 0 is to use the javascript padStart function.

Example:

lastPart < 10 ? "0": "" is the same as
lastPart.toString().padStart(2, '0')

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

2020-09-23 20:10 UTC, tonydavydets commented on frontend/react/src/components/fields/Integer.js
> +    const parsed = parseInt(numeric, 10);
lines 9 and 10 seem redundant.  either one will do

2020-09-23 20:15 UTC, tonydavydets commented on frontend/react/src/components/fields/Question.js
> +]);
I may be wrong, but I think I see a pattern... couldn't we infer the value of the map by:

* splitting the key string by '_'
* init capping each array member
* joining together by "" (blank) character

this would eliminate the need to hardcode map like that.  

what do you guys think?

2020-09-23 20:19 UTC, mgwalker commented on frontend/react/src/components/fields/Question.js
> +]);
In a scenario like this, I prefer being explicit over inferring. The inference incorporates assumptions and logic that future developers won't need to bother with if we're just explicit.

2020-09-23 20:21 UTC, mgwalker commented on frontend/react/src/components/fields/Integer.js
> +    const parsed = parseInt(numeric, 10);
They're not redundant. The `+` unary operator will convert to a number – including floating point – but `parseInt` will convert to an integer. This difference is necessary to catch the situation where the user types `1.`. If we only use one or the other, that will pass and we won't display an error. However, the UI won't update to show the `.`. Since we're eating user input, we need to show an error, so we need to handle that condition.

2020-09-23 20:22 UTC, tonydavydets commented on frontend/react/src/components/layout/PageInfo.js
> +    </h1>
Should we make both dates configurable (stored in props / state) as opposed to hardcoding in template source?

2020-09-23 20:24 UTC, mgwalker commented
@tonydavydets 

```
parseInt(id.split("-").pop()) + 1).toString().padStart(2, "0");
```

The `pop()`ed value is a string, so that `+ 1` will be the same string with the number 1 appended to it. The popped value needs to be converted to a number before doing math on it.

I like the suggestion to use `padStart`!

2020-09-23 20:26 UTC, mgwalker commented on frontend/react/src/components/layout/PageInfo.js
> +    </h1>
Eventually, definitely. But out of scope of this PR.

2020-09-23 20:27 UTC, tonydavydets reviewed
other than a few minor things / questions I pointed out, looks great overall.  I don't think any of them will drastically affect functionality; more something for us to think about from the point of standardizing / optimizing.  looks like a ton of work went into it.  seems very well thought out.

2020-09-23 20:29 UTC, tonydavydets commented
@mgwalker 
"...Conciseness is not always more readable or obvious, and I prefer the latter..."

couldn't agree more lol.  wasn't sure what we were going for here (sometimes less lines is called for).

but I agree 100%

2020-09-23 20:32 UTC, tonydavydets commented on frontend/react/src/components/fields/Question.js
> +]);
ok, sounds good.  so, what I'm getting overall is, we're shooting for clarity over reducing lines of code.

will keep it in mind when writing / reviewing code 👍

2020-09-23 20:48 UTC, tonydavydets approved these changes

2020-09-23 20:52 UTC, jgillis1 approved these changes

2020-09-23 21:35 UTC, mgwalker commented
Making a note here: I was going to make the switch over to `String.padStart`, but it's not supported in IE. I don't know what our browser support requirements are or what polyfills we're using, so for now, I'm just going to leave it alone.

2020-09-23 21:35 UTC, merged

2020-09-23 21:37 UTC, alewoo28 commented
Hey Greg, 
I pulled this branch down and tested functionality.I did my best to look through all 53 files but its a lot of code. 

I want to double check the functionality of the DateRange. 
I'm not able to edit any of the fields after all 4 have been entered. Have you seen this issue as well? (Section 2a, question 3B)

I'm also having some trouble with the percentage fields. (Section 3C, question 1a). I can only enter and delete one character at a time before having to click away and click back to be able to type.

2020-09-23 22:40 UTC, mgwalker commented
I'll take a look at those two issues first thing tomorrow!

2020-09-24 15:31 UTC, mgwalker commented
I've confirmed the DateRange issue. Looks like it's in the old DateRange component (or something going wonky in the combination of the old and new ones).