ability to override okta authentication for localhost / cartsdemo
CMSgov/cms-carts-seds pull request #629
Opened 2020-09-22 18:57 UTC by tonydavydets

2020-09-22 22:48 UTC, jgillis1 approved these changes

2020-09-23 08:59 UTC, mblevins-collabralink commented
A reasonable hack.

2020-09-23 09:00 UTC, mblevins-collabralink approved these changes
Should be safe on localhost.

2020-09-23 11:11 UTC, jgillis1 commented
QA Review has been completed and the PR is ready for 18F review.

2020-09-23 14:16 UTC, mgwalker requested changes
Aside from parsing out the domain, the implementation here is fine by me.

Open question about whether we should bypass auth altogether on cartsdemo, which I think is one we should get @StephanieCoppel or @kaitlin to weigh in on.

Marking request changes for now and we can resolve it once we've got a clear answer!

2020-09-23 14:16 UTC, mgwalker commented on frontend/react/src/wrapSecurity.js
> +  const domain = urlParts[2];
```suggestion
  // *** !!!! THIS PART WAS ADDED / SLIGHTLY AUGMENTED
  // *** pull apart the url using '/' as a separating delimiter
  const domain = window.location.host;
```

`window.location` is a [Location object](https://developer.mozilla.org/en-US/docs/Web/API/Location/host) and it already conveniently has properties for the various bits of the location. 🙂

Though as I think about it more, I'm wondering if instead of checking `localhost` for the domain, maybe it'd be better to check if `process.env.NODE_ENV === 'development'`. It's provided automatically by create-react-app and it'll also cover the case where someone happens to navigate locally using `127.0.0.1` or whatever else.

You'd still need to check the domain for cartsdemo, but I'm not sure we should bypass authentication on cartsdemo. Since it will be writing to a live database, I'm concerned about a bad actor finding the site, putting in profane or offensive content, and then someone else being exposed to it.

2020-09-23 16:47 UTC, tonydavydets commented on frontend/react/src/wrapSecurity.js
> +  const domain = urlParts[2];
yeah sure.  this was just a quick hack I came up with (more for devs really).  thoughts anyone?

2020-11-10 16:38 UTC, closed without merging