Add program_type and program_names to State model
CMSgov/cms-carts-seds pull request #696
Opened 2020-09-29 06:29 UTC by tadhg-ohiggins

Program type and names
Belong to states not users.
Add them to the states.

- Add `program_type` and `program_names` to `State` model.
- Add list of `program_type` options.
- Add `State`, `ACS`, `FMAP`, and `AppUser` to models visible in Django admin.
- Use `state-fixture-data.csv` for populating the state fixtures with the new program_type and program_names fields.
- Remove American Samoa, Guam, the Northern Mariana Islands, Puerto Rico, and the Virgin Islands from the fixture data, because none of them report to CARTS.

This is related to #206 because separating what's associated with states versus users is necessary before developing the models/endpoints, and users are going to be associated with states and pull program type and program names from the states, so we need to populate that info.

2020-09-29 06:30 UTC, tadhg-ohiggins commented
FWIW I did test this against a running database with prior data in it rather than a completely new database, and the migrations and fixtures worked fine, but that's not a guarantee that that'll work in staging…

2020-09-29 06:46 UTC, tadhg-ohiggins commented
@kaitlin @erinzstrenio @StephanieCoppel I removed American Samoa, Guam, the Northern Mariana Islands, Puerto Rico, and the Virgin Islands from the FMAP and state data, let me know if we need to add them back for some reason.

2020-09-29 13:05 UTC, StephanieCoppel commented
> @kaitlin @erinzstrenio @StephanieCoppel I removed American Samoa, Guam, the Northern Mariana Islands, Puerto Rico, and the Virgin Islands from the FMAP and state data, let me know if we need to add them back for some reason.

@tadhg-ohiggins we do not need to add those back, thanks for removing those. thanks!

2020-09-29 13:29 UTC, mgwalker approved these changes
Looks fine to me, but having @timoballard's eyes on `generate_fixtures` wouldn't be the worst idea.

2020-09-29 13:29 UTC, mgwalker commented on frontend/api_postgres/carts/carts_api/models.py
> +        help_text="percentage of uninsured     children",
The result of reformatting the code, I'm guessing? Does the backslash preserve whitespace?

2020-09-29 14:25 UTC, timoballard approved these changes

2020-09-29 14:34 UTC, timoballard requested changes

2020-09-29 14:34 UTC, timoballard commented on frontend/api_postgres/carts/carts_api/model_utils.py
> +    ("state_user", "State User"),
this reordering results in a new migration being generated - I think we should either back this change out or commit the migration

2020-09-29 16:23 UTC, tadhg-ohiggins commented on frontend/api_postgres/carts/carts_api/model_utils.py
> +    ("state_user", "State User"),
I'll back it out.

2020-09-29 23:50 UTC, tadhg-ohiggins commented
@timoballard Could you verify that this version doesn't trigger a migration? If it's good to go after that, feel free to merge it in.

2020-09-30 13:27 UTC, jgillis1 commented
As a note, please be aware that states can change/add/remove programs year over year. So the 2020 program name and type could be different in 2022 (i.e. the 2020 program is discontinued and replaced with a new program). Does that need to be accounted for in this model or would it be handled in the database only?

2020-09-30 13:31 UTC, timoballard commented
@tadhg-ohiggins - just checked, no migrations now 👍

2020-09-30 16:25 UTC, tadhg-ohiggins commented
@jgillis1 Yes, I was thinking about this—do we need to track state historical program type, or would it be enough to have that info in their answers for previous years? So if MA is a combo state in 2020 but a separate_chip state in 2021, would it be enough for their CARTS report itself to have that data but their state info in the DB say they're separate_chip? I was assuming that having the info in the reports would be sufficient. @StephanieCoppel any thoughts on this?

2020-09-30 16:45 UTC, jgillis1 commented
We probably don't (though the current system does) but Program Type drives
behavior in the app in terms of what is shown and not shown in some
sections. You're saying that the form then would be the source of truth for
program type and name rather than what you are loading into the state
model? And, follow up question, if that is so, what is the purpose of
adding them to the state model? (Just curious there)


*Jenna Gillis*
Full Stack Developer, ACME Dev Team Lead
CollabraLink Technologies, Inc.
jgillis@collabralink.com
*C:* 443.807-7580


On Wed, Sep 30, 2020 at 12:25 PM tadhg-ohiggins <notifications@github.com>
wrote:

> @jgillis1 <https://github.com/jgillis1> Yes, I was thinking about this—do
> we need to track state historical program type, or would it be enough to
> have that info in their answers for previous years? So if MA is a combo
> state in 2020 but a separate_chip state in 2021, would it be enough for
> their CARTS report itself to have that data but their state info in the DB
> say they're separate_chip? I was assuming that having the info in the
> reports would be sufficient. @StephanieCoppel
> <https://github.com/StephanieCoppel> any thoughts on this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/cms-carts-seds/pull/696#issuecomment-701499395>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIUO2LINEJHWK6COIPPDQ3LSINLYFANCNFSM4R5L5MDA>
> .
>

2020-09-30 16:47 UTC, jgillis1 commented
@tadhg-ohiggins We probably don't need it historically (though the current system does) but Program Type drives behavior in the app in terms of what is shown and not shown in some sections. You're saying that the form then would be the source of truth for program type and name rather than what you are loading into the state model? And, follow up question, if that is so, what is the purpose of adding them to the state model? (Just curious there)

2020-09-30 16:54 UTC, tadhg-ohiggins commented
The state model would be the source of truth for active forms. So if MA is combo in 2020 that would be shown in the state model. But if MA had been separate_chip in any prior year, that would only be captured in the MA report for that year.

2020-09-30 16:54 UTC, timoballard approved these changes

2020-09-30 16:55 UTC, merged

2020-10-01 12:48 UTC, jgillis1 commented
@tadhg-ohiggins Could you add comments to the model RE: the above so the set up is easy to find and reference in the future?