American community survey
CMSgov/cms-carts-seds pull request #750
Opened 2020-10-02 19:47 UTC by andrewadcock

Decided to follow the same pattern as the lookupFMAP action since this information only needs to be on one page. This has an added benefit of being easily manipulated for the front-end; flexibility with table headers, ordering, etc. 

JSON for section 2 was modified to show the previous 5 years of data. The percent change non-interactive table and its child, were moved because synthesized table cannot handle child questions 

Updated _form.scss to add spacing around tables.

2020-10-05 11:55 UTC, jgillis1 approved these changes

2020-10-05 11:55 UTC, jgillis1 commented on frontend/api_postgres/utils/section-schemas/backend-json-section-2.json
> +                  "rows": [[-1.7]]
Should this be a synthesized value instead? Or some calculation instead of hard coded. If you think we need a new ticket to address this specifically, let me know.

2020-10-05 12:22 UTC, mblevins-collabralink approved these changes

2020-10-05 13:04 UTC, tonydavydets approved these changes

2020-10-05 20:28 UTC, jgillis1 approved these changes

2020-10-05 20:30 UTC, jgillis1 commented
QA Review has been completed and the PR is ready for 18F review.

2020-10-06 16:16 UTC, mgwalker requested changes
Looks nice and clean to me! A pair of small change requests, and one open question (which I will happily defer to your judgement on, especially since "leave it alone" is less work).

2020-10-06 16:16 UTC, mgwalker commented on frontend/react/src/util/synthesize.js
> +const lookupAcs = (state, args) => {
Go ahead and destructure `args` here so it's clearer later on what they're doing:

```js
const lookupAcs = (state, [ffy, acsProperty]) => {
```

2020-10-06 16:16 UTC, mgwalker commented on frontend/react/src/util/synthesize.js
> +const compareACS = (state, args) => {
Same story

```js
const compareAcs = (state, [ffy, acsProperty]) => {
```

2020-10-06 19:37 UTC, mgwalker approved these changes

2020-10-06 19:38 UTC, merged