Filter Federal User Homepage
CMSgov/cms-carts-seds pull request #986
Opened 2020-12-14 20:39 UTC by TGriesemer

Addresses ticket # [2445](https://qmacbis.atlassian.net/browse/OY2-2445) for filtering the co_user/bus_user homepage. 

3 multi select drop downs were added (State, Year, Status)

2020-12-17 18:27 UTC, jgillis1 requested changes

2020-12-17 18:27 UTC, jgillis1 commented on frontend/react/src/components/sections/homepage/CMSHomepage.js
> +    { label: "Submitted", value: "submitted" },
Do we need "Submitted"? I don't think that's a status a CARTS report can enter into.

2020-12-17 18:27 UTC, jgillis1 commented on frontend/react/src/components/sections/homepage/CMSHomepage.js
> +    { label: "Uncertified", value: "uncertified" },
Do we need this as an option since the uncertify action puts the status back to "In Progress"?

2020-12-17 18:27 UTC, jgillis1 commented on frontend/react/src/components/sections/homepage/CMSHomepage.js
> +                    {/* <Multiselect
Could you remove the commented out pieces that are not being used here?

2020-12-18 17:48 UTC, TGriesemer commented on frontend/react/src/components/sections/homepage/CMSHomepage.js
> +    { label: "Submitted", value: "submitted" },
I don't know if we "need" them but since they were already there I figured I would leave them. I will remove them and if we need them back we can add them in.

2020-12-18 17:48 UTC, TGriesemer commented on frontend/react/src/components/sections/homepage/CMSHomepage.js
> +    { label: "Uncertified", value: "uncertified" },
same as above.

2020-12-18 20:56 UTC, jgillis1 approved these changes

2020-12-18 20:57 UTC, merged